exclude: |
  (?x)^(
     \.idea/.*
  )$

default_stages: [ commit ]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: pretty-format-json
        args:
          - --autofix

#  - repo: https://github.com/pre-commit/pre-commit-hooks
#    rev: v4.6.0
#    hooks:
#      - id: no-commit-to-branch
#        name: Prevent commit to main branch
#        args: [ --branch, main ]
#
#  - repo: https://github.com/astral-sh/ruff-pre-commit
#    # Ruff version.
#    rev: v0.4.8
#    hooks:
#      # Run the linter.
#      - id: ruff
#        args: [ --fix ]
#      # Run the formatter.
#      - id: ruff-format
