name: 'release_helper'
description: 'A tool to check related tickets are in a ready state for deployment.'

inputs:
  github-token:
    description: 'release_helper github token'
    required: true
  linear-token:
    description: 'release_helper linear token'
    required: true
  slack-bot-token:
    description: 'release_helper slack bot token'
    required: true
  slack-channel-name:
    description: 'release_helper slack channel name, include the #'
    required: true

#outputs:
#  result:
#    description: 'release_helper result'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    HELPER_GITHUB_TOKEN: ${{ inputs.github-token }}
    HELPER_LINEAR_TOKEN: ${{ inputs.linear-token }}
    HELPER_SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
    HELPER_SLACK_CHANNEL_NAME: ${{ inputs.slack-channel-name }}

branding:
    color: 'blue'
    icon: 'play-circle'
