# Generated by ariadne-codegen
# Source: release_helper/issue_management/linear/schema.graphql

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    Day,
    IssueRelationType,
    ProjectNotificationSubscriptionType,
    ProjectUpdateHealthType,
    ProjectUpdateReminderFrequency,
    PushSubscriptionType,
    SlaStatus,
    UserRoleType,
    ViewPreferencesType,
    ViewType,
)


class IssueImportMappingInput(BaseModel):
    users: Optional[Any] = None
    workflow_states: Optional[Any] = Field(alias="workflowStates", default=None)
    epics: Optional[Any] = None


class SamlConfigurationInput(BaseModel):
    sso_signing_cert: Optional[str] = Field(alias="ssoSigningCert", default=None)
    sso_endpoint: Optional[str] = Field(alias="ssoEndpoint", default=None)
    sso_binding: Optional[str] = Field(alias="ssoBinding", default=None)
    sso_sign_algo: Optional[str] = Field(alias="ssoSignAlgo", default=None)
    issuer_entity_id: Optional[str] = Field(alias="issuerEntityId", default=None)


class IntercomSettingsInput(BaseModel):
    send_note_on_status_change: Optional[bool] = Field(
        alias="sendNoteOnStatusChange", default=None
    )
    send_note_on_comment: Optional[bool] = Field(
        alias="sendNoteOnComment", default=None
    )
    automate_ticket_reopening_on_completion: Optional[bool] = Field(
        alias="automateTicketReopeningOnCompletion", default=None
    )
    automate_ticket_reopening_on_cancellation: Optional[bool] = Field(
        alias="automateTicketReopeningOnCancellation", default=None
    )
    automate_ticket_reopening_on_comment: Optional[bool] = Field(
        alias="automateTicketReopeningOnComment", default=None
    )


class FrontSettingsInput(BaseModel):
    send_note_on_status_change: Optional[bool] = Field(
        alias="sendNoteOnStatusChange", default=None
    )
    send_note_on_comment: Optional[bool] = Field(
        alias="sendNoteOnComment", default=None
    )
    automate_ticket_reopening_on_completion: Optional[bool] = Field(
        alias="automateTicketReopeningOnCompletion", default=None
    )
    automate_ticket_reopening_on_cancellation: Optional[bool] = Field(
        alias="automateTicketReopeningOnCancellation", default=None
    )
    automate_ticket_reopening_on_comment: Optional[bool] = Field(
        alias="automateTicketReopeningOnComment", default=None
    )


class SlackPostSettingsInput(BaseModel):
    channel: str
    channel_id: str = Field(alias="channelId")
    configuration_url: str = Field(alias="configurationUrl")


class GitHubSettingsInput(BaseModel):
    org_avatar_url: str = Field(alias="orgAvatarUrl")
    org_login: str = Field(alias="orgLogin")


class GoogleSheetsSettingsInput(BaseModel):
    spreadsheet_id: str = Field(alias="spreadsheetId")
    spreadsheet_url: str = Field(alias="spreadsheetUrl")
    sheet_id: float = Field(alias="sheetId")
    updated_issues_at: Any = Field(alias="updatedIssuesAt")


class JiraProjectDataInput(BaseModel):
    id: str
    key: str
    name: str


class JiraLinearMappingInput(BaseModel):
    jira_project_id: str = Field(alias="jiraProjectId")
    linear_team_id: str = Field(alias="linearTeamId")


class JiraSettingsInput(BaseModel):
    project_mapping: Optional[List["JiraLinearMappingInput"]] = Field(
        alias="projectMapping", default=None
    )
    projects: List["JiraProjectDataInput"]


class NotionSettingsInput(BaseModel):
    workspace_id: str = Field(alias="workspaceId")
    workspace_name: str = Field(alias="workspaceName")


class SentrySettingsInput(BaseModel):
    organization_slug: str = Field(alias="organizationSlug")


class ZendeskSettingsInput(BaseModel):
    send_note_on_status_change: Optional[bool] = Field(
        alias="sendNoteOnStatusChange", default=None
    )
    send_note_on_comment: Optional[bool] = Field(
        alias="sendNoteOnComment", default=None
    )
    automate_ticket_reopening_on_completion: Optional[bool] = Field(
        alias="automateTicketReopeningOnCompletion", default=None
    )
    automate_ticket_reopening_on_cancellation: Optional[bool] = Field(
        alias="automateTicketReopeningOnCancellation", default=None
    )
    automate_ticket_reopening_on_comment: Optional[bool] = Field(
        alias="automateTicketReopeningOnComment", default=None
    )
    subdomain: str
    url: str
    bot_user_id: Optional[str] = Field(alias="botUserId", default=None)


class IntegrationSettingsInput(BaseModel):
    slack_post: Optional["SlackPostSettingsInput"] = Field(
        alias="slackPost", default=None
    )
    slack_project_post: Optional["SlackPostSettingsInput"] = Field(
        alias="slackProjectPost", default=None
    )
    slack_org_project_updates_post: Optional["SlackPostSettingsInput"] = Field(
        alias="slackOrgProjectUpdatesPost", default=None
    )
    google_sheets: Optional["GoogleSheetsSettingsInput"] = Field(
        alias="googleSheets", default=None
    )
    git_hub: Optional["GitHubSettingsInput"] = Field(alias="gitHub", default=None)
    sentry: Optional["SentrySettingsInput"] = None
    zendesk: Optional["ZendeskSettingsInput"] = None
    intercom: Optional["IntercomSettingsInput"] = None
    front: Optional["FrontSettingsInput"] = None
    jira: Optional["JiraSettingsInput"] = None
    notion: Optional["NotionSettingsInput"] = None


class BooleanComparator(BaseModel):
    eq: Optional[bool] = None
    neq: Optional[bool] = None


class DateComparator(BaseModel):
    eq: Optional[Any] = None
    neq: Optional[Any] = None
    in_: Optional[List[Any]] = Field(alias="in", default=None)
    nin: Optional[List[Any]] = None
    lt: Optional[Any] = None
    lte: Optional[Any] = None
    gt: Optional[Any] = None
    gte: Optional[Any] = None


class NullableDateComparator(BaseModel):
    eq: Optional[Any] = None
    neq: Optional[Any] = None
    in_: Optional[List[Any]] = Field(alias="in", default=None)
    nin: Optional[List[Any]] = None
    null: Optional[bool] = None
    lt: Optional[Any] = None
    lte: Optional[Any] = None
    gt: Optional[Any] = None
    gte: Optional[Any] = None


class IDComparator(BaseModel):
    eq: Optional[str] = None
    neq: Optional[str] = None
    in_: Optional[List[str]] = Field(alias="in", default=None)
    nin: Optional[List[str]] = None


class StringComparator(BaseModel):
    eq: Optional[str] = None
    neq: Optional[str] = None
    in_: Optional[List[str]] = Field(alias="in", default=None)
    nin: Optional[List[str]] = None
    eq_ignore_case: Optional[str] = Field(alias="eqIgnoreCase", default=None)
    neq_ignore_case: Optional[str] = Field(alias="neqIgnoreCase", default=None)
    starts_with: Optional[str] = Field(alias="startsWith", default=None)
    not_starts_with: Optional[str] = Field(alias="notStartsWith", default=None)
    ends_with: Optional[str] = Field(alias="endsWith", default=None)
    not_ends_with: Optional[str] = Field(alias="notEndsWith", default=None)
    contains: Optional[str] = None
    contains_ignore_case: Optional[str] = Field(
        alias="containsIgnoreCase", default=None
    )
    not_contains: Optional[str] = Field(alias="notContains", default=None)
    not_contains_ignore_case: Optional[str] = Field(
        alias="notContainsIgnoreCase", default=None
    )


class NullableStringComparator(BaseModel):
    eq: Optional[str] = None
    neq: Optional[str] = None
    in_: Optional[List[str]] = Field(alias="in", default=None)
    nin: Optional[List[str]] = None
    null: Optional[bool] = None
    eq_ignore_case: Optional[str] = Field(alias="eqIgnoreCase", default=None)
    neq_ignore_case: Optional[str] = Field(alias="neqIgnoreCase", default=None)
    starts_with: Optional[str] = Field(alias="startsWith", default=None)
    not_starts_with: Optional[str] = Field(alias="notStartsWith", default=None)
    ends_with: Optional[str] = Field(alias="endsWith", default=None)
    not_ends_with: Optional[str] = Field(alias="notEndsWith", default=None)
    contains: Optional[str] = None
    contains_ignore_case: Optional[str] = Field(
        alias="containsIgnoreCase", default=None
    )
    not_contains: Optional[str] = Field(alias="notContains", default=None)
    not_contains_ignore_case: Optional[str] = Field(
        alias="notContainsIgnoreCase", default=None
    )


class TeamFilter(BaseModel):
    id: Optional["IDComparator"] = None
    created_at: Optional["DateComparator"] = Field(alias="createdAt", default=None)
    updated_at: Optional["DateComparator"] = Field(alias="updatedAt", default=None)
    name: Optional["StringComparator"] = None
    key: Optional["StringComparator"] = None
    description: Optional["NullableStringComparator"] = None
    issues: Optional["IssueCollectionFilter"] = None
    and_: Optional[List["TeamFilter"]] = Field(alias="and", default=None)
    or_: Optional[List["TeamFilter"]] = Field(alias="or", default=None)


class NumberComparator(BaseModel):
    eq: Optional[float] = None
    neq: Optional[float] = None
    in_: Optional[List[float]] = Field(alias="in", default=None)
    nin: Optional[List[float]] = None
    lt: Optional[float] = None
    lte: Optional[float] = None
    gt: Optional[float] = None
    gte: Optional[float] = None


class NullableNumberComparator(BaseModel):
    eq: Optional[float] = None
    neq: Optional[float] = None
    in_: Optional[List[float]] = Field(alias="in", default=None)
    nin: Optional[List[float]] = None
    null: Optional[bool] = None
    lt: Optional[float] = None
    lte: Optional[float] = None
    gt: Optional[float] = None
    gte: Optional[float] = None


class UserFilter(BaseModel):
    id: Optional["IDComparator"] = None
    created_at: Optional["DateComparator"] = Field(alias="createdAt", default=None)
    updated_at: Optional["DateComparator"] = Field(alias="updatedAt", default=None)
    name: Optional["StringComparator"] = None
    display_name: Optional["StringComparator"] = Field(
        alias="displayName", default=None
    )
    email: Optional["StringComparator"] = None
    active: Optional["BooleanComparator"] = None
    assigned_issues: Optional["IssueCollectionFilter"] = Field(
        alias="assignedIssues", default=None
    )
    admin: Optional["BooleanComparator"] = None
    is_me: Optional["BooleanComparator"] = Field(alias="isMe", default=None)
    and_: Optional[List["UserFilter"]] = Field(alias="and", default=None)
    or_: Optional[List["UserFilter"]] = Field(alias="or", default=None)


class NullableUserFilter(BaseModel):
    id: Optional["IDComparator"] = None
    created_at: Optional["DateComparator"] = Field(alias="createdAt", default=None)
    updated_at: Optional["DateComparator"] = Field(alias="updatedAt", default=None)
    name: Optional["StringComparator"] = None
    display_name: Optional["StringComparator"] = Field(
        alias="displayName", default=None
    )
    email: Optional["StringComparator"] = None
    active: Optional["BooleanComparator"] = None
    assigned_issues: Optional["IssueCollectionFilter"] = Field(
        alias="assignedIssues", default=None
    )
    admin: Optional["BooleanComparator"] = None
    is_me: Optional["BooleanComparator"] = Field(alias="isMe", default=None)
    null: Optional[bool] = None
    and_: Optional[List["NullableUserFilter"]] = Field(alias="and", default=None)
    or_: Optional[List["NullableUserFilter"]] = Field(alias="or", default=None)


class UserCollectionFilter(BaseModel):
    id: Optional["IDComparator"] = None
    created_at: Optional["DateComparator"] = Field(alias="createdAt", default=None)
    updated_at: Optional["DateComparator"] = Field(alias="updatedAt", default=None)
    name: Optional["StringComparator"] = None
    display_name: Optional["StringComparator"] = Field(
        alias="displayName", default=None
    )
    email: Optional["StringComparator"] = None
    active: Optional["BooleanComparator"] = None
    assigned_issues: Optional["IssueCollectionFilter"] = Field(
        alias="assignedIssues", default=None
    )
    admin: Optional["BooleanComparator"] = None
    is_me: Optional["BooleanComparator"] = Field(alias="isMe", default=None)
    and_: Optional[List["UserCollectionFilter"]] = Field(alias="and", default=None)
    or_: Optional[List["UserCollectionFilter"]] = Field(alias="or", default=None)
    some: Optional["UserFilter"] = None
    every: Optional["UserFilter"] = None
    length: Optional["NumberComparator"] = None


class IssueLabelFilter(BaseModel):
    id: Optional["IDComparator"] = None
    created_at: Optional["DateComparator"] = Field(alias="createdAt", default=None)
    updated_at: Optional["DateComparator"] = Field(alias="updatedAt", default=None)
    name: Optional["StringComparator"] = None
    creator: Optional["NullableUserFilter"] = None
    team: Optional["TeamFilter"] = None
    parent: Optional["IssueLabelFilter"] = None
    and_: Optional[List["IssueLabelFilter"]] = Field(alias="and", default=None)
    or_: Optional[List["IssueLabelFilter"]] = Field(alias="or", default=None)


class IssueLabelCollectionFilter(BaseModel):
    id: Optional["IDComparator"] = None
    created_at: Optional["DateComparator"] = Field(alias="createdAt", default=None)
    updated_at: Optional["DateComparator"] = Field(alias="updatedAt", default=None)
    name: Optional["StringComparator"] = None
    creator: Optional["NullableUserFilter"] = None
    team: Optional["TeamFilter"] = None
    parent: Optional["IssueLabelFilter"] = None
    and_: Optional[List["IssueLabelCollectionFilter"]] = Field(
        alias="and", default=None
    )
    or_: Optional[List["IssueLabelCollectionFilter"]] = Field(alias="or", default=None)
    some: Optional["IssueLabelFilter"] = None
    every: Optional["IssueLabelFilter"] = None
    length: Optional["NumberComparator"] = None


class TimelessDateComparator(BaseModel):
    eq: Optional[Any] = None
    neq: Optional[Any] = None
    in_: Optional[List[Any]] = Field(alias="in", default=None)
    nin: Optional[List[Any]] = None
    lt: Optional[Any] = None
    lte: Optional[Any] = None
    gt: Optional[Any] = None
    gte: Optional[Any] = None


class NullableTimelessDateComparator(BaseModel):
    eq: Optional[Any] = None
    neq: Optional[Any] = None
    in_: Optional[List[Any]] = Field(alias="in", default=None)
    nin: Optional[List[Any]] = None
    null: Optional[bool] = None
    lt: Optional[Any] = None
    lte: Optional[Any] = None
    gt: Optional[Any] = None
    gte: Optional[Any] = None


class CycleFilter(BaseModel):
    id: Optional["IDComparator"] = None
    created_at: Optional["DateComparator"] = Field(alias="createdAt", default=None)
    updated_at: Optional["DateComparator"] = Field(alias="updatedAt", default=None)
    number: Optional["NumberComparator"] = None
    name: Optional["StringComparator"] = None
    starts_at: Optional["DateComparator"] = Field(alias="startsAt", default=None)
    ends_at: Optional["DateComparator"] = Field(alias="endsAt", default=None)
    completed_at: Optional["DateComparator"] = Field(alias="completedAt", default=None)
    is_active: Optional["BooleanComparator"] = Field(alias="isActive", default=None)
    is_next: Optional["BooleanComparator"] = Field(alias="isNext", default=None)
    is_previous: Optional["BooleanComparator"] = Field(alias="isPrevious", default=None)
    is_future: Optional["BooleanComparator"] = Field(alias="isFuture", default=None)
    is_past: Optional["BooleanComparator"] = Field(alias="isPast", default=None)
    team: Optional["TeamFilter"] = None
    issues: Optional["IssueCollectionFilter"] = None
    and_: Optional[List["CycleFilter"]] = Field(alias="and", default=None)
    or_: Optional[List["CycleFilter"]] = Field(alias="or", default=None)


class NullableCycleFilter(BaseModel):
    id: Optional["IDComparator"] = None
    created_at: Optional["DateComparator"] = Field(alias="createdAt", default=None)
    updated_at: Optional["DateComparator"] = Field(alias="updatedAt", default=None)
    number: Optional["NumberComparator"] = None
    name: Optional["StringComparator"] = None
    starts_at: Optional["DateComparator"] = Field(alias="startsAt", default=None)
    ends_at: Optional["DateComparator"] = Field(alias="endsAt", default=None)
    completed_at: Optional["DateComparator"] = Field(alias="completedAt", default=None)
    is_active: Optional["BooleanComparator"] = Field(alias="isActive", default=None)
    is_next: Optional["BooleanComparator"] = Field(alias="isNext", default=None)
    is_previous: Optional["BooleanComparator"] = Field(alias="isPrevious", default=None)
    is_future: Optional["BooleanComparator"] = Field(alias="isFuture", default=None)
    is_past: Optional["BooleanComparator"] = Field(alias="isPast", default=None)
    team: Optional["TeamFilter"] = None
    issues: Optional["IssueCollectionFilter"] = None
    null: Optional[bool] = None
    and_: Optional[List["NullableCycleFilter"]] = Field(alias="and", default=None)
    or_: Optional[List["NullableCycleFilter"]] = Field(alias="or", default=None)


class RoadmapFilter(BaseModel):
    id: Optional["IDComparator"] = None
    created_at: Optional["DateComparator"] = Field(alias="createdAt", default=None)
    updated_at: Optional["DateComparator"] = Field(alias="updatedAt", default=None)
    name: Optional["StringComparator"] = None
    slug_id: Optional["StringComparator"] = Field(alias="slugId", default=None)
    creator: Optional["UserFilter"] = None
    and_: Optional[List["RoadmapFilter"]] = Field(alias="and", default=None)
    or_: Optional[List["RoadmapFilter"]] = Field(alias="or", default=None)


class RoadmapCollectionFilter(BaseModel):
    id: Optional["IDComparator"] = None
    created_at: Optional["DateComparator"] = Field(alias="createdAt", default=None)
    updated_at: Optional["DateComparator"] = Field(alias="updatedAt", default=None)
    name: Optional["StringComparator"] = None
    slug_id: Optional["StringComparator"] = Field(alias="slugId", default=None)
    creator: Optional["UserFilter"] = None
    and_: Optional[List["RoadmapCollectionFilter"]] = Field(alias="and", default=None)
    or_: Optional[List["RoadmapCollectionFilter"]] = Field(alias="or", default=None)
    some: Optional["RoadmapFilter"] = None
    every: Optional["RoadmapFilter"] = None
    length: Optional["NumberComparator"] = None


class ProjectFilter(BaseModel):
    id: Optional["IDComparator"] = None
    created_at: Optional["DateComparator"] = Field(alias="createdAt", default=None)
    updated_at: Optional["DateComparator"] = Field(alias="updatedAt", default=None)
    name: Optional["StringComparator"] = None
    slug_id: Optional["StringComparator"] = Field(alias="slugId", default=None)
    state: Optional["StringComparator"] = None
    start_date: Optional["NullableDateComparator"] = Field(
        alias="startDate", default=None
    )
    target_date: Optional["NullableDateComparator"] = Field(
        alias="targetDate", default=None
    )
    creator: Optional["UserFilter"] = None
    lead: Optional["NullableUserFilter"] = None
    members: Optional["UserFilter"] = None
    issues: Optional["IssueCollectionFilter"] = None
    roadmaps: Optional["RoadmapCollectionFilter"] = None
    and_: Optional[List["ProjectFilter"]] = Field(alias="and", default=None)
    or_: Optional[List["ProjectFilter"]] = Field(alias="or", default=None)


class NullableProjectFilter(BaseModel):
    id: Optional["IDComparator"] = None
    created_at: Optional["DateComparator"] = Field(alias="createdAt", default=None)
    updated_at: Optional["DateComparator"] = Field(alias="updatedAt", default=None)
    name: Optional["StringComparator"] = None
    slug_id: Optional["StringComparator"] = Field(alias="slugId", default=None)
    state: Optional["StringComparator"] = None
    start_date: Optional["NullableDateComparator"] = Field(
        alias="startDate", default=None
    )
    target_date: Optional["NullableDateComparator"] = Field(
        alias="targetDate", default=None
    )
    creator: Optional["UserFilter"] = None
    lead: Optional["NullableUserFilter"] = None
    members: Optional["UserFilter"] = None
    issues: Optional["IssueCollectionFilter"] = None
    roadmaps: Optional["RoadmapCollectionFilter"] = None
    null: Optional[bool] = None
    and_: Optional[List["NullableProjectFilter"]] = Field(alias="and", default=None)
    or_: Optional[List["NullableProjectFilter"]] = Field(alias="or", default=None)


class ProjectCollectionFilter(BaseModel):
    id: Optional["IDComparator"] = None
    created_at: Optional["DateComparator"] = Field(alias="createdAt", default=None)
    updated_at: Optional["DateComparator"] = Field(alias="updatedAt", default=None)
    name: Optional["StringComparator"] = None
    slug_id: Optional["StringComparator"] = Field(alias="slugId", default=None)
    state: Optional["StringComparator"] = None
    start_date: Optional["NullableDateComparator"] = Field(
        alias="startDate", default=None
    )
    target_date: Optional["NullableDateComparator"] = Field(
        alias="targetDate", default=None
    )
    creator: Optional["UserFilter"] = None
    lead: Optional["NullableUserFilter"] = None
    members: Optional["UserFilter"] = None
    issues: Optional["IssueCollectionFilter"] = None
    roadmaps: Optional["RoadmapCollectionFilter"] = None
    and_: Optional[List["ProjectCollectionFilter"]] = Field(alias="and", default=None)
    or_: Optional[List["ProjectCollectionFilter"]] = Field(alias="or", default=None)
    some: Optional["ProjectFilter"] = None
    every: Optional["ProjectFilter"] = None
    length: Optional["NumberComparator"] = None


class WorkflowStateFilter(BaseModel):
    id: Optional["IDComparator"] = None
    created_at: Optional["DateComparator"] = Field(alias="createdAt", default=None)
    updated_at: Optional["DateComparator"] = Field(alias="updatedAt", default=None)
    name: Optional["StringComparator"] = None
    description: Optional["StringComparator"] = None
    position: Optional["NumberComparator"] = None
    type: Optional["StringComparator"] = None
    team: Optional["TeamFilter"] = None
    issues: Optional["IssueCollectionFilter"] = None
    and_: Optional[List["WorkflowStateFilter"]] = Field(alias="and", default=None)
    or_: Optional[List["WorkflowStateFilter"]] = Field(alias="or", default=None)


class SourceTypeComparator(BaseModel):
    eq: Optional[str] = None
    neq: Optional[str] = None
    in_: Optional[List[str]] = Field(alias="in", default=None)
    nin: Optional[List[str]] = None
    eq_ignore_case: Optional[str] = Field(alias="eqIgnoreCase", default=None)
    neq_ignore_case: Optional[str] = Field(alias="neqIgnoreCase", default=None)
    starts_with: Optional[str] = Field(alias="startsWith", default=None)
    not_starts_with: Optional[str] = Field(alias="notStartsWith", default=None)
    ends_with: Optional[str] = Field(alias="endsWith", default=None)
    not_ends_with: Optional[str] = Field(alias="notEndsWith", default=None)
    contains: Optional[str] = None
    contains_ignore_case: Optional[str] = Field(
        alias="containsIgnoreCase", default=None
    )
    not_contains: Optional[str] = Field(alias="notContains", default=None)
    not_contains_ignore_case: Optional[str] = Field(
        alias="notContainsIgnoreCase", default=None
    )


class AttachmentFilter(BaseModel):
    id: Optional["IDComparator"] = None
    created_at: Optional["DateComparator"] = Field(alias="createdAt", default=None)
    updated_at: Optional["DateComparator"] = Field(alias="updatedAt", default=None)
    title: Optional["StringComparator"] = None
    subtitle: Optional["NullableStringComparator"] = None
    url: Optional["StringComparator"] = None
    creator: Optional["NullableUserFilter"] = None
    source_type: Optional["SourceTypeComparator"] = Field(
        alias="sourceType", default=None
    )
    and_: Optional[List["AttachmentFilter"]] = Field(alias="and", default=None)
    or_: Optional[List["AttachmentFilter"]] = Field(alias="or", default=None)


class AttachmentCollectionFilter(BaseModel):
    id: Optional["IDComparator"] = None
    created_at: Optional["DateComparator"] = Field(alias="createdAt", default=None)
    updated_at: Optional["DateComparator"] = Field(alias="updatedAt", default=None)
    title: Optional["StringComparator"] = None
    subtitle: Optional["NullableStringComparator"] = None
    url: Optional["StringComparator"] = None
    creator: Optional["NullableUserFilter"] = None
    source_type: Optional["SourceTypeComparator"] = Field(
        alias="sourceType", default=None
    )
    and_: Optional[List["AttachmentCollectionFilter"]] = Field(
        alias="and", default=None
    )
    or_: Optional[List["AttachmentCollectionFilter"]] = Field(alias="or", default=None)
    some: Optional["AttachmentFilter"] = None
    every: Optional["AttachmentFilter"] = None
    length: Optional["NumberComparator"] = None


class CommentFilter(BaseModel):
    id: Optional["IDComparator"] = None
    created_at: Optional["DateComparator"] = Field(alias="createdAt", default=None)
    updated_at: Optional["DateComparator"] = Field(alias="updatedAt", default=None)
    body: Optional["StringComparator"] = None
    user: Optional["UserFilter"] = None
    issue: Optional["IssueFilter"] = None
    and_: Optional[List["CommentFilter"]] = Field(alias="and", default=None)
    or_: Optional[List["CommentFilter"]] = Field(alias="or", default=None)


class CommentCollectionFilter(BaseModel):
    id: Optional["IDComparator"] = None
    created_at: Optional["DateComparator"] = Field(alias="createdAt", default=None)
    updated_at: Optional["DateComparator"] = Field(alias="updatedAt", default=None)
    body: Optional["StringComparator"] = None
    user: Optional["UserFilter"] = None
    issue: Optional["IssueFilter"] = None
    and_: Optional[List["CommentCollectionFilter"]] = Field(alias="and", default=None)
    or_: Optional[List["CommentCollectionFilter"]] = Field(alias="or", default=None)
    some: Optional["CommentFilter"] = None
    every: Optional["CommentFilter"] = None
    length: Optional["NumberComparator"] = None


class ContentComparator(BaseModel):
    contains: Optional[str] = None
    not_contains: Optional[str] = Field(alias="notContains", default=None)


class EstimateComparator(BaseModel):
    eq: Optional[float] = None
    neq: Optional[float] = None
    in_: Optional[List[float]] = Field(alias="in", default=None)
    nin: Optional[List[float]] = None
    null: Optional[bool] = None
    lt: Optional[float] = None
    lte: Optional[float] = None
    gt: Optional[float] = None
    gte: Optional[float] = None
    or_: Optional[List["NullableNumberComparator"]] = Field(alias="or", default=None)
    and_: Optional[List["NullableNumberComparator"]] = Field(alias="and", default=None)


class RelationExistsComparator(BaseModel):
    eq: Optional[bool] = None
    neq: Optional[bool] = None


class NullableProjectMilestoneFilter(BaseModel):
    id: Optional["IDComparator"] = None
    created_at: Optional["DateComparator"] = Field(alias="createdAt", default=None)
    updated_at: Optional["DateComparator"] = Field(alias="updatedAt", default=None)
    null: Optional[bool] = None
    and_: Optional[List["NullableProjectMilestoneFilter"]] = Field(
        alias="and", default=None
    )
    or_: Optional[List["NullableProjectMilestoneFilter"]] = Field(
        alias="or", default=None
    )


class SlaStatusComparator(BaseModel):
    eq: Optional[SlaStatus] = None
    neq: Optional[SlaStatus] = None
    in_: Optional[List[SlaStatus]] = Field(alias="in", default=None)
    nin: Optional[List[SlaStatus]] = None
    null: Optional[bool] = None


class NullableIssueFilter(BaseModel):
    id: Optional["IDComparator"] = None
    created_at: Optional["DateComparator"] = Field(alias="createdAt", default=None)
    updated_at: Optional["DateComparator"] = Field(alias="updatedAt", default=None)
    number: Optional["NumberComparator"] = None
    title: Optional["StringComparator"] = None
    description: Optional["NullableStringComparator"] = None
    priority: Optional["NullableNumberComparator"] = None
    estimate: Optional["EstimateComparator"] = None
    started_at: Optional["NullableDateComparator"] = Field(
        alias="startedAt", default=None
    )
    triaged_at: Optional["NullableDateComparator"] = Field(
        alias="triagedAt", default=None
    )
    completed_at: Optional["NullableDateComparator"] = Field(
        alias="completedAt", default=None
    )
    canceled_at: Optional["NullableDateComparator"] = Field(
        alias="canceledAt", default=None
    )
    auto_closed_at: Optional["NullableDateComparator"] = Field(
        alias="autoClosedAt", default=None
    )
    auto_archived_at: Optional["NullableDateComparator"] = Field(
        alias="autoArchivedAt", default=None
    )
    due_date: Optional["NullableTimelessDateComparator"] = Field(
        alias="dueDate", default=None
    )
    snoozed_until_at: Optional["NullableDateComparator"] = Field(
        alias="snoozedUntilAt", default=None
    )
    assignee: Optional["NullableUserFilter"] = None
    creator: Optional["NullableUserFilter"] = None
    parent: Optional["NullableIssueFilter"] = None
    snoozed_by: Optional["NullableUserFilter"] = Field(alias="snoozedBy", default=None)
    labels: Optional["IssueLabelCollectionFilter"] = None
    subscribers: Optional["UserCollectionFilter"] = None
    team: Optional["TeamFilter"] = None
    project_milestone: Optional["NullableProjectMilestoneFilter"] = Field(
        alias="projectMilestone", default=None
    )
    comments: Optional["CommentCollectionFilter"] = None
    cycle: Optional["NullableCycleFilter"] = None
    project: Optional["NullableProjectFilter"] = None
    state: Optional["WorkflowStateFilter"] = None
    children: Optional["IssueCollectionFilter"] = None
    attachments: Optional["AttachmentCollectionFilter"] = None
    searchable_content: Optional["ContentComparator"] = Field(
        alias="searchableContent", default=None
    )
    has_related_relations: Optional["RelationExistsComparator"] = Field(
        alias="hasRelatedRelations", default=None
    )
    has_duplicate_relations: Optional["RelationExistsComparator"] = Field(
        alias="hasDuplicateRelations", default=None
    )
    has_blocked_by_relations: Optional["RelationExistsComparator"] = Field(
        alias="hasBlockedByRelations", default=None
    )
    has_blocking_relations: Optional["RelationExistsComparator"] = Field(
        alias="hasBlockingRelations", default=None
    )
    sla_status: Optional["SlaStatusComparator"] = Field(alias="slaStatus", default=None)
    null: Optional[bool] = None
    and_: Optional[List["NullableIssueFilter"]] = Field(alias="and", default=None)
    or_: Optional[List["NullableIssueFilter"]] = Field(alias="or", default=None)


class IssueFilter(BaseModel):
    id: Optional["IDComparator"] = None
    created_at: Optional["DateComparator"] = Field(alias="createdAt", default=None)
    updated_at: Optional["DateComparator"] = Field(alias="updatedAt", default=None)
    number: Optional["NumberComparator"] = None
    title: Optional["StringComparator"] = None
    description: Optional["NullableStringComparator"] = None
    priority: Optional["NullableNumberComparator"] = None
    estimate: Optional["EstimateComparator"] = None
    started_at: Optional["NullableDateComparator"] = Field(
        alias="startedAt", default=None
    )
    triaged_at: Optional["NullableDateComparator"] = Field(
        alias="triagedAt", default=None
    )
    completed_at: Optional["NullableDateComparator"] = Field(
        alias="completedAt", default=None
    )
    canceled_at: Optional["NullableDateComparator"] = Field(
        alias="canceledAt", default=None
    )
    auto_closed_at: Optional["NullableDateComparator"] = Field(
        alias="autoClosedAt", default=None
    )
    auto_archived_at: Optional["NullableDateComparator"] = Field(
        alias="autoArchivedAt", default=None
    )
    due_date: Optional["NullableTimelessDateComparator"] = Field(
        alias="dueDate", default=None
    )
    snoozed_until_at: Optional["NullableDateComparator"] = Field(
        alias="snoozedUntilAt", default=None
    )
    assignee: Optional["NullableUserFilter"] = None
    creator: Optional["NullableUserFilter"] = None
    parent: Optional["NullableIssueFilter"] = None
    snoozed_by: Optional["NullableUserFilter"] = Field(alias="snoozedBy", default=None)
    labels: Optional["IssueLabelCollectionFilter"] = None
    subscribers: Optional["UserCollectionFilter"] = None
    team: Optional["TeamFilter"] = None
    project_milestone: Optional["NullableProjectMilestoneFilter"] = Field(
        alias="projectMilestone", default=None
    )
    comments: Optional["CommentCollectionFilter"] = None
    cycle: Optional["NullableCycleFilter"] = None
    project: Optional["NullableProjectFilter"] = None
    state: Optional["WorkflowStateFilter"] = None
    children: Optional["IssueCollectionFilter"] = None
    attachments: Optional["AttachmentCollectionFilter"] = None
    searchable_content: Optional["ContentComparator"] = Field(
        alias="searchableContent", default=None
    )
    has_related_relations: Optional["RelationExistsComparator"] = Field(
        alias="hasRelatedRelations", default=None
    )
    has_duplicate_relations: Optional["RelationExistsComparator"] = Field(
        alias="hasDuplicateRelations", default=None
    )
    has_blocked_by_relations: Optional["RelationExistsComparator"] = Field(
        alias="hasBlockedByRelations", default=None
    )
    has_blocking_relations: Optional["RelationExistsComparator"] = Field(
        alias="hasBlockingRelations", default=None
    )
    sla_status: Optional["SlaStatusComparator"] = Field(alias="slaStatus", default=None)
    and_: Optional[List["IssueFilter"]] = Field(alias="and", default=None)
    or_: Optional[List["IssueFilter"]] = Field(alias="or", default=None)


class IssueCollectionFilter(BaseModel):
    id: Optional["IDComparator"] = None
    created_at: Optional["DateComparator"] = Field(alias="createdAt", default=None)
    updated_at: Optional["DateComparator"] = Field(alias="updatedAt", default=None)
    number: Optional["NumberComparator"] = None
    title: Optional["StringComparator"] = None
    description: Optional["NullableStringComparator"] = None
    priority: Optional["NullableNumberComparator"] = None
    estimate: Optional["EstimateComparator"] = None
    started_at: Optional["NullableDateComparator"] = Field(
        alias="startedAt", default=None
    )
    triaged_at: Optional["NullableDateComparator"] = Field(
        alias="triagedAt", default=None
    )
    completed_at: Optional["NullableDateComparator"] = Field(
        alias="completedAt", default=None
    )
    canceled_at: Optional["NullableDateComparator"] = Field(
        alias="canceledAt", default=None
    )
    auto_closed_at: Optional["NullableDateComparator"] = Field(
        alias="autoClosedAt", default=None
    )
    auto_archived_at: Optional["NullableDateComparator"] = Field(
        alias="autoArchivedAt", default=None
    )
    due_date: Optional["NullableTimelessDateComparator"] = Field(
        alias="dueDate", default=None
    )
    snoozed_until_at: Optional["NullableDateComparator"] = Field(
        alias="snoozedUntilAt", default=None
    )
    assignee: Optional["NullableUserFilter"] = None
    creator: Optional["NullableUserFilter"] = None
    parent: Optional["NullableIssueFilter"] = None
    snoozed_by: Optional["NullableUserFilter"] = Field(alias="snoozedBy", default=None)
    labels: Optional["IssueLabelCollectionFilter"] = None
    subscribers: Optional["UserCollectionFilter"] = None
    team: Optional["TeamFilter"] = None
    project_milestone: Optional["NullableProjectMilestoneFilter"] = Field(
        alias="projectMilestone", default=None
    )
    comments: Optional["CommentCollectionFilter"] = None
    cycle: Optional["NullableCycleFilter"] = None
    project: Optional["NullableProjectFilter"] = None
    state: Optional["WorkflowStateFilter"] = None
    children: Optional["IssueCollectionFilter"] = None
    attachments: Optional["AttachmentCollectionFilter"] = None
    searchable_content: Optional["ContentComparator"] = Field(
        alias="searchableContent", default=None
    )
    has_related_relations: Optional["RelationExistsComparator"] = Field(
        alias="hasRelatedRelations", default=None
    )
    has_duplicate_relations: Optional["RelationExistsComparator"] = Field(
        alias="hasDuplicateRelations", default=None
    )
    has_blocked_by_relations: Optional["RelationExistsComparator"] = Field(
        alias="hasBlockedByRelations", default=None
    )
    has_blocking_relations: Optional["RelationExistsComparator"] = Field(
        alias="hasBlockingRelations", default=None
    )
    sla_status: Optional["SlaStatusComparator"] = Field(alias="slaStatus", default=None)
    and_: Optional[List["IssueCollectionFilter"]] = Field(alias="and", default=None)
    or_: Optional[List["IssueCollectionFilter"]] = Field(alias="or", default=None)
    some: Optional["IssueFilter"] = None
    every: Optional["IssueFilter"] = None
    length: Optional["NumberComparator"] = None


class WorkflowCondition(BaseModel):
    issue_filter: Optional["IssueFilter"] = Field(alias="issueFilter", default=None)
    project_filter: Optional["ProjectFilter"] = Field(
        alias="projectFilter", default=None
    )


class EventCreateInput(BaseModel):
    category: str
    subject: str
    target_id: Optional[str] = Field(alias="targetId", default=None)
    value: Optional[float] = None
    data: Optional[Any] = None


class ApiKeyCreateInput(BaseModel):
    id: Optional[str] = None
    label: str
    key: str


class AttachmentCreateInput(BaseModel):
    id: Optional[str] = None
    title: str
    subtitle: Optional[str] = None
    url: str
    issue_id: str = Field(alias="issueId")
    icon_url: Optional[str] = Field(alias="iconUrl", default=None)
    metadata: Optional[Any] = None
    group_by_source: Optional[bool] = Field(alias="groupBySource", default=None)
    comment_body: Optional[str] = Field(alias="commentBody", default=None)
    comment_body_data: Optional[Any] = Field(alias="commentBodyData", default=None)
    create_as_user: Optional[str] = Field(alias="createAsUser", default=None)


class AttachmentUpdateInput(BaseModel):
    title: str
    subtitle: Optional[str] = None
    metadata: Optional[Any] = None
    icon_url: Optional[str] = Field(alias="iconUrl", default=None)


class AuditEntryFilter(BaseModel):
    id: Optional["IDComparator"] = None
    created_at: Optional["DateComparator"] = Field(alias="createdAt", default=None)
    updated_at: Optional["DateComparator"] = Field(alias="updatedAt", default=None)
    type: Optional["StringComparator"] = None
    ip: Optional["StringComparator"] = None
    country_code: Optional["StringComparator"] = Field(
        alias="countryCode", default=None
    )
    actor: Optional["NullableUserFilter"] = None


class OnboardingCustomerSurvey(BaseModel):
    company_role: Optional[str] = Field(alias="companyRole", default=None)
    company_size: Optional[str] = Field(alias="companySize", default=None)


class CreateOrganizationInput(BaseModel):
    name: str
    url_key: str = Field(alias="urlKey")
    domain_access: Optional[bool] = Field(alias="domainAccess", default=None)
    timezone: Optional[str] = None
    utm: Optional[str] = None


class JoinOrganizationInput(BaseModel):
    organization_id: str = Field(alias="organizationId")


class EmailUserAccountAuthChallengeInput(BaseModel):
    email: str
    is_desktop: Optional[bool] = Field(alias="isDesktop", default=None)
    client_auth_code: Optional[str] = Field(alias="clientAuthCode", default=None)
    signup_code: Optional[str] = Field(alias="signupCode", default=None)


class TokenUserAccountAuthInput(BaseModel):
    email: str
    token: str
    timezone: str
    team_ids_to_join: Optional[List[str]] = Field(alias="teamIdsToJoin", default=None)


class GoogleUserAccountAuthInput(BaseModel):
    code: str
    redirect_uri: Optional[str] = Field(alias="redirectUri", default=None)
    timezone: str
    team_ids_to_join: Optional[List[str]] = Field(alias="teamIdsToJoin", default=None)
    signup_code: Optional[str] = Field(alias="signupCode", default=None)


class CommentCreateInput(BaseModel):
    id: Optional[str] = None
    body: Optional[str] = None
    body_data: Optional[Any] = Field(alias="bodyData", default=None)
    issue_id: str = Field(alias="issueId")
    parent_id: Optional[str] = Field(alias="parentId", default=None)
    create_as_user: Optional[str] = Field(alias="createAsUser", default=None)
    display_icon_url: Optional[str] = Field(alias="displayIconUrl", default=None)
    created_at: Optional[Any] = Field(alias="createdAt", default=None)
    do_not_subscribe_to_issue: Optional[bool] = Field(
        alias="doNotSubscribeToIssue", default=None
    )


class CommentUpdateInput(BaseModel):
    body: Optional[str] = None
    body_data: Optional[Any] = Field(alias="bodyData", default=None)


class ContactCreateInput(BaseModel):
    type: str
    message: str
    operating_system: Optional[str] = Field(alias="operatingSystem", default=None)
    browser: Optional[str] = None
    device: Optional[str] = None
    client_version: Optional[str] = Field(alias="clientVersion", default=None)
    disappointment_rating: Optional[int] = Field(
        alias="disappointmentRating", default=None
    )


class ContactSalesCreateInput(BaseModel):
    name: str
    email: str
    message: Optional[str] = None


class CustomViewCreateInput(BaseModel):
    id: Optional[str] = None
    name: str
    description: Optional[str] = None
    icon: Optional[str] = None
    color: Optional[str] = None
    team_id: Optional[str] = Field(alias="teamId", default=None)
    owner_id: Optional[str] = Field(alias="ownerId", default=None)
    filters: Optional[Any] = None
    filter_data: Optional[Any] = Field(alias="filterData", default=None)
    project_filter_data: Optional[Any] = Field(alias="projectFilterData", default=None)
    shared: Optional[bool] = None


class CustomViewUpdateInput(BaseModel):
    name: Optional[str] = None
    description: Optional[str] = None
    icon: Optional[str] = None
    color: Optional[str] = None
    team_id: Optional[str] = Field(alias="teamId", default=None)
    owner_id: Optional[str] = Field(alias="ownerId", default=None)
    filters: Optional[Any] = None
    filter_data: Optional[Any] = Field(alias="filterData", default=None)
    project_filter_data: Optional[Any] = Field(alias="projectFilterData", default=None)
    shared: Optional[bool] = None


class CycleCreateInput(BaseModel):
    id: Optional[str] = None
    name: Optional[str] = None
    description: Optional[str] = None
    team_id: str = Field(alias="teamId")
    starts_at: Any = Field(alias="startsAt")
    ends_at: Any = Field(alias="endsAt")
    completed_at: Optional[Any] = Field(alias="completedAt", default=None)


class CycleUpdateInput(BaseModel):
    name: Optional[str] = None
    description: Optional[str] = None
    starts_at: Optional[Any] = Field(alias="startsAt", default=None)
    ends_at: Optional[Any] = Field(alias="endsAt", default=None)
    completed_at: Optional[Any] = Field(alias="completedAt", default=None)


class DocumentCreateInput(BaseModel):
    id: Optional[str] = None
    title: str
    icon: Optional[str] = None
    color: Optional[str] = None
    content_data: Optional[Any] = Field(alias="contentData", default=None)
    content: Optional[str] = None
    project_id: str = Field(alias="projectId")


class DocumentUpdateInput(BaseModel):
    title: Optional[str] = None
    icon: Optional[str] = None
    color: Optional[str] = None
    content_data: Optional[Any] = Field(alias="contentData", default=None)
    content: Optional[str] = None
    project_id: Optional[str] = Field(alias="projectId", default=None)


class EmailSubscribeInput(BaseModel):
    email: str


class EmailUnsubscribeInput(BaseModel):
    type: str
    token: str
    user_id: str = Field(alias="userId")


class EmojiCreateInput(BaseModel):
    id: Optional[str] = None
    name: str
    url: str


class FavoriteCreateInput(BaseModel):
    id: Optional[str] = None
    folder_name: Optional[str] = Field(alias="folderName", default=None)
    parent_id: Optional[str] = Field(alias="parentId", default=None)
    issue_id: Optional[str] = Field(alias="issueId", default=None)
    project_id: Optional[str] = Field(alias="projectId", default=None)
    project_team_id: Optional[str] = Field(alias="projectTeamId", default=None)
    predefined_view_type: Optional[str] = Field(
        alias="predefinedViewType", default=None
    )
    predefined_view_team_id: Optional[str] = Field(
        alias="predefinedViewTeamId", default=None
    )
    cycle_id: Optional[str] = Field(alias="cycleId", default=None)
    custom_view_id: Optional[str] = Field(alias="customViewId", default=None)
    document_id: Optional[str] = Field(alias="documentId", default=None)
    roadmap_id: Optional[str] = Field(alias="roadmapId", default=None)
    label_id: Optional[str] = Field(alias="labelId", default=None)
    sort_order: Optional[float] = Field(alias="sortOrder", default=None)


class FavoriteUpdateInput(BaseModel):
    sort_order: Optional[float] = Field(alias="sortOrder", default=None)
    parent_id: Optional[str] = Field(alias="parentId", default=None)
    folder_name: Optional[str] = Field(alias="folderName", default=None)


class IntegrationRequestInput(BaseModel):
    email: Optional[str] = None
    name: str


class JiraConfigurationInput(BaseModel):
    access_token: str = Field(alias="accessToken")
    email: str
    hostname: str
    project: Optional[str] = None


class AirbyteConfigurationInput(BaseModel):
    api_key: str = Field(alias="apiKey")


class IntegrationsSettingsCreateInput(BaseModel):
    slack_issue_created: Optional[bool] = Field(alias="slackIssueCreated", default=None)
    slack_issue_new_comment: Optional[bool] = Field(
        alias="slackIssueNewComment", default=None
    )
    slack_issue_status_changed_done: Optional[bool] = Field(
        alias="slackIssueStatusChangedDone", default=None
    )
    slack_issue_status_changed_all: Optional[bool] = Field(
        alias="slackIssueStatusChangedAll", default=None
    )
    slack_project_update_created: Optional[bool] = Field(
        alias="slackProjectUpdateCreated", default=None
    )
    slack_project_update_created_to_team: Optional[bool] = Field(
        alias="slackProjectUpdateCreatedToTeam", default=None
    )
    slack_project_update_created_to_workspace: Optional[bool] = Field(
        alias="slackProjectUpdateCreatedToWorkspace", default=None
    )
    slack_issue_added_to_triage: Optional[bool] = Field(
        alias="slackIssueAddedToTriage", default=None
    )
    slack_issue_sla_high_risk: Optional[bool] = Field(
        alias="slackIssueSlaHighRisk", default=None
    )
    slack_issue_sla_breached: Optional[bool] = Field(
        alias="slackIssueSlaBreached", default=None
    )
    id: Optional[str] = None
    team_id: Optional[str] = Field(alias="teamId", default=None)
    project_id: Optional[str] = Field(alias="projectId", default=None)


class IntegrationsSettingsUpdateInput(BaseModel):
    slack_issue_created: Optional[bool] = Field(alias="slackIssueCreated", default=None)
    slack_issue_new_comment: Optional[bool] = Field(
        alias="slackIssueNewComment", default=None
    )
    slack_issue_status_changed_done: Optional[bool] = Field(
        alias="slackIssueStatusChangedDone", default=None
    )
    slack_issue_status_changed_all: Optional[bool] = Field(
        alias="slackIssueStatusChangedAll", default=None
    )
    slack_project_update_created: Optional[bool] = Field(
        alias="slackProjectUpdateCreated", default=None
    )
    slack_project_update_created_to_team: Optional[bool] = Field(
        alias="slackProjectUpdateCreatedToTeam", default=None
    )
    slack_project_update_created_to_workspace: Optional[bool] = Field(
        alias="slackProjectUpdateCreatedToWorkspace", default=None
    )
    slack_issue_added_to_triage: Optional[bool] = Field(
        alias="slackIssueAddedToTriage", default=None
    )
    slack_issue_sla_high_risk: Optional[bool] = Field(
        alias="slackIssueSlaHighRisk", default=None
    )
    slack_issue_sla_breached: Optional[bool] = Field(
        alias="slackIssueSlaBreached", default=None
    )


class IntegrationTemplateCreateInput(BaseModel):
    id: Optional[str] = None
    integration_id: str = Field(alias="integrationId")
    template_id: str = Field(alias="templateId")


class IssueImportUpdateInput(BaseModel):
    mapping: Any


class IssueLabelCreateInput(BaseModel):
    id: Optional[str] = None
    name: str
    description: Optional[str] = None
    color: Optional[str] = None
    parent_id: Optional[str] = Field(alias="parentId", default=None)
    team_id: Optional[str] = Field(alias="teamId", default=None)


class IssueLabelUpdateInput(BaseModel):
    name: Optional[str] = None
    description: Optional[str] = None
    parent_id: Optional[str] = Field(alias="parentId", default=None)
    color: Optional[str] = None


class IssueRelationCreateInput(BaseModel):
    id: Optional[str] = None
    type: IssueRelationType
    issue_id: str = Field(alias="issueId")
    related_issue_id: str = Field(alias="relatedIssueId")


class IssueRelationUpdateInput(BaseModel):
    type: Optional[str] = None
    issue_id: Optional[str] = Field(alias="issueId", default=None)
    related_issue_id: Optional[str] = Field(alias="relatedIssueId", default=None)


class IssueCreateInput(BaseModel):
    id: Optional[str] = None
    title: str
    description: Optional[str] = None
    description_data: Optional[Any] = Field(alias="descriptionData", default=None)
    assignee_id: Optional[str] = Field(alias="assigneeId", default=None)
    parent_id: Optional[str] = Field(alias="parentId", default=None)
    priority: Optional[int] = None
    estimate: Optional[int] = None
    subscriber_ids: Optional[List[str]] = Field(alias="subscriberIds", default=None)
    label_ids: Optional[List[str]] = Field(alias="labelIds", default=None)
    team_id: str = Field(alias="teamId")
    cycle_id: Optional[str] = Field(alias="cycleId", default=None)
    project_id: Optional[str] = Field(alias="projectId", default=None)
    project_milestone_id: Optional[str] = Field(
        alias="projectMilestoneId", default=None
    )
    state_id: Optional[str] = Field(alias="stateId", default=None)
    reference_comment_id: Optional[str] = Field(
        alias="referenceCommentId", default=None
    )
    board_order: Optional[float] = Field(alias="boardOrder", default=None)
    sort_order: Optional[float] = Field(alias="sortOrder", default=None)
    sub_issue_sort_order: Optional[float] = Field(
        alias="subIssueSortOrder", default=None
    )
    due_date: Optional[Any] = Field(alias="dueDate", default=None)
    create_as_user: Optional[str] = Field(alias="createAsUser", default=None)
    display_icon_url: Optional[str] = Field(alias="displayIconUrl", default=None)
    created_at: Optional[Any] = Field(alias="createdAt", default=None)
    sla_breaches_at: Optional[Any] = Field(alias="slaBreachesAt", default=None)


class IssueUpdateInput(BaseModel):
    title: Optional[str] = None
    description: Optional[str] = None
    description_data: Optional[Any] = Field(alias="descriptionData", default=None)
    assignee_id: Optional[str] = Field(alias="assigneeId", default=None)
    parent_id: Optional[str] = Field(alias="parentId", default=None)
    priority: Optional[int] = None
    estimate: Optional[int] = None
    subscriber_ids: Optional[List[str]] = Field(alias="subscriberIds", default=None)
    label_ids: Optional[List[str]] = Field(alias="labelIds", default=None)
    team_id: Optional[str] = Field(alias="teamId", default=None)
    cycle_id: Optional[str] = Field(alias="cycleId", default=None)
    project_id: Optional[str] = Field(alias="projectId", default=None)
    project_milestone_id: Optional[str] = Field(
        alias="projectMilestoneId", default=None
    )
    state_id: Optional[str] = Field(alias="stateId", default=None)
    board_order: Optional[float] = Field(alias="boardOrder", default=None)
    sort_order: Optional[float] = Field(alias="sortOrder", default=None)
    sub_issue_sort_order: Optional[float] = Field(
        alias="subIssueSortOrder", default=None
    )
    due_date: Optional[Any] = Field(alias="dueDate", default=None)
    trashed: Optional[bool] = None
    sla_breaches_at: Optional[Any] = Field(alias="slaBreachesAt", default=None)
    snoozed_until_at: Optional[Any] = Field(alias="snoozedUntilAt", default=None)
    snoozed_by_id: Optional[str] = Field(alias="snoozedById", default=None)


class NotificationUpdateInput(BaseModel):
    read_at: Optional[Any] = Field(alias="readAt", default=None)
    snoozed_until_at: Optional[Any] = Field(alias="snoozedUntilAt", default=None)
    project_update_id: Optional[str] = Field(alias="projectUpdateId", default=None)


class NotificationSubscriptionCreateInput(BaseModel):
    id: Optional[str] = None
    team_id: Optional[str] = Field(alias="teamId", default=None)
    project_id: Optional[str] = Field(alias="projectId", default=None)
    project_notification_subscription_type: Optional[
        ProjectNotificationSubscriptionType
    ] = Field(alias="projectNotificationSubscriptionType", default=None)
    team_notification_subscription_types: Optional[List[str]] = Field(
        alias="teamNotificationSubscriptionTypes", default=None
    )


class NotificationSubscriptionUpdateInput(BaseModel):
    project_notification_subscription_type: Optional[
        ProjectNotificationSubscriptionType
    ] = Field(alias="projectNotificationSubscriptionType", default=None)
    team_notification_subscription_types: Optional[List[str]] = Field(
        alias="teamNotificationSubscriptionTypes", default=None
    )


class OrganizationDomainCreateInput(BaseModel):
    id: Optional[str] = None
    name: str
    verification_email: Optional[str] = Field(alias="verificationEmail", default=None)
    auth_type: Optional[str] = Field(alias="authType", default="general")


class OrganizationDomainVerificationInput(BaseModel):
    organization_domain_id: str = Field(alias="organizationDomainId")
    verification_code: str = Field(alias="verificationCode")


class OrganizationInviteCreateInput(BaseModel):
    id: Optional[str] = None
    email: str
    role: Optional[UserRoleType] = UserRoleType.user
    message: Optional[str] = None
    team_ids: Optional[List[str]] = Field(alias="teamIds", default=None)


class OrganizationInviteUpdateInput(BaseModel):
    team_ids: List[str] = Field(alias="teamIds")


class UpdateOrganizationInput(BaseModel):
    name: Optional[str] = None
    logo_url: Optional[str] = Field(alias="logoUrl", default=None)
    url_key: Optional[str] = Field(alias="urlKey", default=None)
    git_branch_format: Optional[str] = Field(alias="gitBranchFormat", default=None)
    git_linkback_messages_enabled: Optional[bool] = Field(
        alias="gitLinkbackMessagesEnabled", default=None
    )
    git_public_linkback_messages_enabled: Optional[bool] = Field(
        alias="gitPublicLinkbackMessagesEnabled", default=None
    )
    roadmap_enabled: Optional[bool] = Field(alias="roadmapEnabled", default=None)
    project_updates_reminder_frequency: Optional[ProjectUpdateReminderFrequency] = (
        Field(alias="projectUpdatesReminderFrequency", default=None)
    )
    project_update_reminders_day: Optional[Day] = Field(
        alias="projectUpdateRemindersDay", default=None
    )
    project_update_reminders_hour: Optional[float] = Field(
        alias="projectUpdateRemindersHour", default=None
    )
    reduced_personal_information: Optional[bool] = Field(
        alias="reducedPersonalInformation", default=None
    )
    oauth_app_review: Optional[bool] = Field(alias="oauthAppReview", default=None)
    linear_preview_flags: Optional[Any] = Field(
        alias="linearPreviewFlags", default=None
    )
    allowed_auth_services: Optional[List[str]] = Field(
        alias="allowedAuthServices", default=None
    )
    sla_enabled: Optional[bool] = Field(alias="slaEnabled", default=None)


class DeleteOrganizationInput(BaseModel):
    deletion_code: str = Field(alias="deletionCode")


class ProjectLinkCreateInput(BaseModel):
    id: Optional[str] = None
    url: str
    label: str
    project_id: str = Field(alias="projectId")


class ProjectLinkUpdateInput(BaseModel):
    url: Optional[str] = None
    label: Optional[str] = None


class ProjectMilestoneCreateInput(BaseModel):
    id: Optional[str] = None
    name: str
    description: Optional[str] = None
    target_date: Optional[Any] = Field(alias="targetDate", default=None)
    project_id: str = Field(alias="projectId")
    sort_order: Optional[float] = Field(alias="sortOrder", default=None)


class ProjectMilestoneUpdateInput(BaseModel):
    name: Optional[str] = None
    description: Optional[str] = None
    target_date: Optional[Any] = Field(alias="targetDate", default=None)
    project_id: Optional[str] = Field(alias="projectId", default=None)
    sort_order: Optional[float] = Field(alias="sortOrder", default=None)


class ProjectCreateInput(BaseModel):
    id: Optional[str] = None
    name: str
    icon: Optional[str] = None
    color: Optional[str] = None
    state: Optional[str] = None
    description: Optional[str] = None
    team_ids: List[str] = Field(alias="teamIds")
    converted_from_issue_id: Optional[str] = Field(
        alias="convertedFromIssueId", default=None
    )
    lead_id: Optional[str] = Field(alias="leadId", default=None)
    member_ids: Optional[List[str]] = Field(alias="memberIds", default=None)
    start_date: Optional[Any] = Field(alias="startDate", default=None)
    target_date: Optional[Any] = Field(alias="targetDate", default=None)
    sort_order: Optional[float] = Field(alias="sortOrder", default=None)


class ProjectUpdateInput(BaseModel):
    state: Optional[str] = None
    name: Optional[str] = None
    description: Optional[str] = None
    converted_from_issue_id: Optional[str] = Field(
        alias="convertedFromIssueId", default=None
    )
    icon: Optional[str] = None
    color: Optional[str] = None
    team_ids: Optional[List[str]] = Field(alias="teamIds", default=None)
    project_update_reminders_paused_until_at: Optional[Any] = Field(
        alias="projectUpdateRemindersPausedUntilAt", default=None
    )
    lead_id: Optional[str] = Field(alias="leadId", default=None)
    member_ids: Optional[List[str]] = Field(alias="memberIds", default=None)
    start_date: Optional[Any] = Field(alias="startDate", default=None)
    target_date: Optional[Any] = Field(alias="targetDate", default=None)
    completed_at: Optional[Any] = Field(alias="completedAt", default=None)
    canceled_at: Optional[Any] = Field(alias="canceledAt", default=None)
    slack_new_issue: Optional[bool] = Field(alias="slackNewIssue", default=None)
    slack_issue_comments: Optional[bool] = Field(
        alias="slackIssueComments", default=None
    )
    slack_issue_statuses: Optional[bool] = Field(
        alias="slackIssueStatuses", default=None
    )
    sort_order: Optional[float] = Field(alias="sortOrder", default=None)


class ProjectUpdateInteractionCreateInput(BaseModel):
    id: Optional[str] = None
    project_update_id: str = Field(alias="projectUpdateId")
    read_at: Any = Field(alias="readAt")


class ProjectUpdateCreateInput(BaseModel):
    id: Optional[str] = None
    body: Optional[str] = None
    body_data: Optional[Any] = Field(alias="bodyData", default=None)
    project_id: str = Field(alias="projectId")
    health: Optional[ProjectUpdateHealthType] = None


class ProjectUpdateUpdateInput(BaseModel):
    body: Optional[str] = None
    body_data: Optional[Any] = Field(alias="bodyData", default=None)
    health: Optional[ProjectUpdateHealthType] = None


class PushSubscriptionCreateInput(BaseModel):
    id: Optional[str] = None
    user_id: str = Field(alias="userId")
    data: str
    type: Optional[PushSubscriptionType] = PushSubscriptionType.web


class ReactionCreateInput(BaseModel):
    id: Optional[str] = None
    emoji: Optional[str] = None
    comment_id: Optional[str] = Field(alias="commentId", default=None)
    project_update_id: Optional[str] = Field(alias="projectUpdateId", default=None)


class RoadmapCreateInput(BaseModel):
    id: Optional[str] = None
    name: str
    description: Optional[str] = None
    owner_id: Optional[str] = Field(alias="ownerId", default=None)
    sort_order: Optional[float] = Field(alias="sortOrder", default=None)
    color: Optional[str] = None


class RoadmapUpdateInput(BaseModel):
    name: Optional[str] = None
    description: Optional[str] = None
    owner_id: Optional[str] = Field(alias="ownerId", default=None)
    sort_order: Optional[float] = Field(alias="sortOrder", default=None)
    color: Optional[str] = None


class RoadmapToProjectCreateInput(BaseModel):
    id: Optional[str] = None
    project_id: str = Field(alias="projectId")
    roadmap_id: str = Field(alias="roadmapId")
    sort_order: Optional[float] = Field(alias="sortOrder", default=None)


class RoadmapToProjectUpdateInput(BaseModel):
    sort_order: Optional[float] = Field(alias="sortOrder", default=None)


class TeamMembershipCreateInput(BaseModel):
    id: Optional[str] = None
    user_id: str = Field(alias="userId")
    team_id: str = Field(alias="teamId")
    owner: Optional[bool] = None
    sort_order: Optional[float] = Field(alias="sortOrder", default=None)


class TeamMembershipUpdateInput(BaseModel):
    owner: Optional[bool] = None
    sort_order: Optional[float] = Field(alias="sortOrder", default=None)


class TeamCreateInput(BaseModel):
    id: Optional[str] = None
    name: str
    description: Optional[str] = None
    key: Optional[str] = None
    icon: Optional[str] = None
    color: Optional[str] = None
    organization_id: Optional[str] = Field(alias="organizationId", default=None)
    cycles_enabled: Optional[bool] = Field(alias="cyclesEnabled", default=None)
    cycle_start_day: Optional[float] = Field(alias="cycleStartDay", default=None)
    cycle_duration: Optional[int] = Field(alias="cycleDuration", default=None)
    cycle_cooldown_time: Optional[int] = Field(alias="cycleCooldownTime", default=None)
    cycle_issue_auto_assign_started: Optional[bool] = Field(
        alias="cycleIssueAutoAssignStarted", default=None
    )
    cycle_issue_auto_assign_completed: Optional[bool] = Field(
        alias="cycleIssueAutoAssignCompleted", default=None
    )
    cycle_lock_to_active: Optional[bool] = Field(
        alias="cycleLockToActive", default=None
    )
    upcoming_cycle_count: Optional[float] = Field(
        alias="upcomingCycleCount", default=None
    )
    triage_enabled: Optional[bool] = Field(alias="triageEnabled", default=None)
    require_priority_to_leave_triage: Optional[bool] = Field(
        alias="requirePriorityToLeaveTriage", default=None
    )
    timezone: Optional[str] = None
    issue_ordering_no_priority_first: Optional[bool] = Field(
        alias="issueOrderingNoPriorityFirst", default=None
    )
    issue_estimation_type: Optional[str] = Field(
        alias="issueEstimationType", default=None
    )
    issue_estimation_allow_zero: Optional[bool] = Field(
        alias="issueEstimationAllowZero", default=None
    )
    issue_sort_order_default_to_bottom: Optional[bool] = Field(
        alias="issueSortOrderDefaultToBottom", default=None
    )
    issue_estimation_extended: Optional[bool] = Field(
        alias="issueEstimationExtended", default=None
    )
    default_issue_estimate: Optional[float] = Field(
        alias="defaultIssueEstimate", default=None
    )
    group_issue_history: Optional[bool] = Field(alias="groupIssueHistory", default=None)
    default_template_for_members_id: Optional[str] = Field(
        alias="defaultTemplateForMembersId", default=None
    )
    default_template_for_non_members_id: Optional[str] = Field(
        alias="defaultTemplateForNonMembersId", default=None
    )
    private: Optional[bool] = None
    auto_close_period: Optional[float] = Field(alias="autoClosePeriod", default=None)
    auto_close_state_id: Optional[str] = Field(alias="autoCloseStateId", default=None)
    auto_archive_period: Optional[float] = Field(
        alias="autoArchivePeriod", default=None
    )
    marked_as_duplicate_workflow_state_id: Optional[str] = Field(
        alias="markedAsDuplicateWorkflowStateId", default=None
    )


class TeamUpdateInput(BaseModel):
    name: Optional[str] = None
    description: Optional[str] = None
    key: Optional[str] = None
    icon: Optional[str] = None
    color: Optional[str] = None
    cycles_enabled: Optional[bool] = Field(alias="cyclesEnabled", default=None)
    cycle_start_day: Optional[float] = Field(alias="cycleStartDay", default=None)
    cycle_duration: Optional[int] = Field(alias="cycleDuration", default=None)
    cycle_cooldown_time: Optional[int] = Field(alias="cycleCooldownTime", default=None)
    cycle_issue_auto_assign_started: Optional[bool] = Field(
        alias="cycleIssueAutoAssignStarted", default=None
    )
    cycle_issue_auto_assign_completed: Optional[bool] = Field(
        alias="cycleIssueAutoAssignCompleted", default=None
    )
    cycle_lock_to_active: Optional[bool] = Field(
        alias="cycleLockToActive", default=None
    )
    cycle_enabled_start_week: Optional[str] = Field(
        alias="cycleEnabledStartWeek", default=None
    )
    upcoming_cycle_count: Optional[float] = Field(
        alias="upcomingCycleCount", default=None
    )
    timezone: Optional[str] = None
    issue_ordering_no_priority_first: Optional[bool] = Field(
        alias="issueOrderingNoPriorityFirst", default=None
    )
    issue_estimation_type: Optional[str] = Field(
        alias="issueEstimationType", default=None
    )
    issue_estimation_allow_zero: Optional[bool] = Field(
        alias="issueEstimationAllowZero", default=None
    )
    issue_sort_order_default_to_bottom: Optional[bool] = Field(
        alias="issueSortOrderDefaultToBottom", default=None
    )
    issue_estimation_extended: Optional[bool] = Field(
        alias="issueEstimationExtended", default=None
    )
    default_issue_estimate: Optional[float] = Field(
        alias="defaultIssueEstimate", default=None
    )
    draft_workflow_state_id: Optional[str] = Field(
        alias="draftWorkflowStateId", default=None
    )
    start_workflow_state_id: Optional[str] = Field(
        alias="startWorkflowStateId", default=None
    )
    review_workflow_state_id: Optional[str] = Field(
        alias="reviewWorkflowStateId", default=None
    )
    merge_workflow_state_id: Optional[str] = Field(
        alias="mergeWorkflowStateId", default=None
    )
    slack_new_issue: Optional[bool] = Field(alias="slackNewIssue", default=None)
    slack_issue_comments: Optional[bool] = Field(
        alias="slackIssueComments", default=None
    )
    slack_issue_statuses: Optional[bool] = Field(
        alias="slackIssueStatuses", default=None
    )
    group_issue_history: Optional[bool] = Field(alias="groupIssueHistory", default=None)
    default_template_for_members_id: Optional[str] = Field(
        alias="defaultTemplateForMembersId", default=None
    )
    default_template_for_non_members_id: Optional[str] = Field(
        alias="defaultTemplateForNonMembersId", default=None
    )
    private: Optional[bool] = None
    triage_enabled: Optional[bool] = Field(alias="triageEnabled", default=None)
    require_priority_to_leave_triage: Optional[bool] = Field(
        alias="requirePriorityToLeaveTriage", default=None
    )
    default_issue_state_id: Optional[str] = Field(
        alias="defaultIssueStateId", default=None
    )
    auto_close_period: Optional[float] = Field(alias="autoClosePeriod", default=None)
    auto_close_state_id: Optional[str] = Field(alias="autoCloseStateId", default=None)
    auto_archive_period: Optional[float] = Field(
        alias="autoArchivePeriod", default=None
    )
    marked_as_duplicate_workflow_state_id: Optional[str] = Field(
        alias="markedAsDuplicateWorkflowStateId", default=None
    )


class TemplateCreateInput(BaseModel):
    id: Optional[str] = None
    type: str
    team_id: Optional[str] = Field(alias="teamId", default=None)
    name: str
    description: Optional[str] = None
    template_data: Any = Field(alias="templateData")


class TemplateUpdateInput(BaseModel):
    name: Optional[str] = None
    description: Optional[str] = None
    team_id: Optional[str] = Field(alias="teamId", default=None)
    template_data: Optional[Any] = Field(alias="templateData", default=None)


class UpdateUserInput(BaseModel):
    name: Optional[str] = None
    display_name: Optional[str] = Field(alias="displayName", default=None)
    avatar_url: Optional[str] = Field(alias="avatarUrl", default=None)
    active: Optional[bool] = None
    disable_reason: Optional[str] = Field(alias="disableReason", default=None)
    admin: Optional[bool] = None
    description: Optional[str] = None
    status_emoji: Optional[str] = Field(alias="statusEmoji", default=None)
    status_label: Optional[str] = Field(alias="statusLabel", default=None)
    status_until_at: Optional[Any] = Field(alias="statusUntilAt", default=None)
    timezone: Optional[str] = None


class UserSettingsUpdateInput(BaseModel):
    settings: Optional[Any] = None
    unsubscribed_from: Optional[List[str]] = Field(
        alias="unsubscribedFrom", default=None
    )
    notification_preferences: Optional[Any] = Field(
        alias="notificationPreferences", default=None
    )


class ViewPreferencesCreateInput(BaseModel):
    id: Optional[str] = None
    type: ViewPreferencesType
    view_type: ViewType = Field(alias="viewType")
    preferences: Any
    insights: Optional[Any] = None
    team_id: Optional[str] = Field(alias="teamId", default=None)
    project_id: Optional[str] = Field(alias="projectId", default=None)
    roadmap_id: Optional[str] = Field(alias="roadmapId", default=None)
    label_id: Optional[str] = Field(alias="labelId", default=None)
    user_id: Optional[str] = Field(alias="userId", default=None)
    cycle_id: Optional[str] = Field(alias="cycleId", default=None)
    custom_view_id: Optional[str] = Field(alias="customViewId", default=None)


class ViewPreferencesUpdateInput(BaseModel):
    preferences: Optional[Any] = None
    insights: Optional[Any] = None


class WebhookCreateInput(BaseModel):
    label: Optional[str] = None
    id: Optional[str] = None
    enabled: Optional[bool] = True
    secret: Optional[str] = None
    url: str
    resource_types: List[str] = Field(alias="resourceTypes")
    team_id: Optional[str] = Field(alias="teamId", default=None)
    all_public_teams: Optional[bool] = Field(alias="allPublicTeams", default=None)


class WebhookUpdateInput(BaseModel):
    label: Optional[str] = None
    secret: Optional[str] = None
    enabled: Optional[bool] = None
    url: Optional[str] = None
    resource_types: Optional[List[str]] = Field(alias="resourceTypes", default=None)


class WorkflowStateCreateInput(BaseModel):
    id: Optional[str] = None
    type: str
    name: str
    color: str
    description: Optional[str] = None
    position: Optional[float] = None
    team_id: str = Field(alias="teamId")


class WorkflowStateUpdateInput(BaseModel):
    name: Optional[str] = None
    color: Optional[str] = None
    description: Optional[str] = None
    position: Optional[float] = None
