# Generated by ariadne-codegen
# Source: release_helper/issue_management/linear/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class Issue(BaseModel):
    issue: "IssueIssue"


class IssueIssue(BaseModel):
    id: str
    title: str
    state: "IssueIssueState"
    assignee: Optional["IssueIssueAssignee"]
    url: str
    identifier: str


class IssueIssueState(BaseModel):
    name: str
    type: str
    id: str
    description: Optional[str]
    color: str


class IssueIssueAssignee(BaseModel):
    id: str
    name: str
    display_name: str = Field(alias="displayName")
    url: str
    email: str


Issue.model_rebuild()
IssueIssue.model_rebuild()
