# Generated by ariadne-codegen
# Source: queries.graphql

from pydantic import Field

from .base_model import BaseModel


class IssueUpdate(BaseModel):
    issue_update: "IssueUpdateIssueUpdate" = Field(alias="issueUpdate")


class IssueUpdateIssueUpdate(BaseModel):
    success: bool


IssueUpdate.model_rebuild()
