# Generated by ariadne-codegen
# Source: release_helper/issue_management/linear/queries.graphql

from typing import List

from pydantic import Field

from .base_model import BaseModel


class State(BaseModel):
    workflow_states: "StateWorkflowStates" = Field(alias="workflowStates")


class StateWorkflowStates(BaseModel):
    nodes: List["StateWorkflowStatesNodes"]


class StateWorkflowStatesNodes(BaseModel):
    id: str


State.model_rebuild()
StateWorkflowStates.model_rebuild()
