# Generated by ariadne-codegen
# Source: src/release_helper/issue_management/linear/schema.graphql

from enum import Enum


class AuthenticationSessionType(str, Enum):
    android = "android"
    desktop = "desktop"
    ios = "ios"
    web = "web"


class ContextViewType(str, Enum):
    activeCycle = "activeCycle"
    activeIssues = "activeIssues"
    backlog = "backlog"
    triage = "triage"
    upcomingCycle = "upcomingCycle"


class CustomerStatusType(str, Enum):
    active = "active"
    inactive = "inactive"


class DateResolutionType(str, Enum):
    halfYear = "halfYear"
    month = "month"
    quarter = "quarter"
    year = "year"


class Day(str, Enum):
    Friday = "Friday"
    Monday = "Monday"
    Saturday = "Saturday"
    Sunday = "Sunday"
    Thursday = "Thursday"
    Tuesday = "Tuesday"
    Wednesday = "Wednesday"


class FacetPageSource(str, Enum):
    projects = "projects"


class FeatureFlagRolloutStageType(str, Enum):
    dev = "dev"
    full = "full"
    internal = "internal"
    partial = "partial"


class GitAutomationStates(str, Enum):
    draft = "draft"
    merge = "merge"
    mergeable = "mergeable"
    review = "review"
    start = "start"


class GithubOrgType(str, Enum):
    organization = "organization"
    user = "user"


class InitiativeStatus(str, Enum):
    Active = "Active"
    Completed = "Completed"
    Planned = "Planned"


class InitiativeTab(str, Enum):
    overview = "overview"
    projects = "projects"


class IntegrationService(str, Enum):
    airbyte = "airbyte"
    discord = "discord"
    email = "email"
    figma = "figma"
    figmaPlugin = "figmaPlugin"
    front = "front"
    github = "github"
    githubCommit = "githubCommit"
    githubEnterpriseServer = "githubEnterpriseServer"
    githubImport = "githubImport"
    githubPersonal = "githubPersonal"
    gitlab = "gitlab"
    googleCalendarPersonal = "googleCalendarPersonal"
    googleSheets = "googleSheets"
    intercom = "intercom"
    jira = "jira"
    jiraPersonal = "jiraPersonal"
    launchDarkly = "launchDarkly"
    loom = "loom"
    notion = "notion"
    opsgenie = "opsgenie"
    pagerDuty = "pagerDuty"
    sentry = "sentry"
    slack = "slack"
    slackAsks = "slackAsks"
    slackCustomViewNotifications = "slackCustomViewNotifications"
    slackOrgProjectUpdatesPost = "slackOrgProjectUpdatesPost"
    slackPersonal = "slackPersonal"
    slackPost = "slackPost"
    slackProjectPost = "slackProjectPost"
    slackProjectUpdatesPost = "slackProjectUpdatesPost"
    zendesk = "zendesk"


class IssueRelationType(str, Enum):
    blocks = "blocks"
    duplicate = "duplicate"
    related = "related"


class OAuthClientApprovalStatus(str, Enum):
    approved = "approved"
    denied = "denied"
    requested = "requested"


class OrganizationDomainAuthType(str, Enum):
    general = "general"
    saml = "saml"


class OrganizationInviteStatus(str, Enum):
    accepted = "accepted"
    expired = "expired"
    pending = "pending"


class PaginationNulls(str, Enum):
    first = "first"
    last = "last"


class PaginationOrderBy(str, Enum):
    createdAt = "createdAt"
    updatedAt = "updatedAt"


class PaginationSortOrder(str, Enum):
    Ascending = "Ascending"
    Descending = "Descending"


class ProjectStatusType(str, Enum):
    backlog = "backlog"
    canceled = "canceled"
    completed = "completed"
    paused = "paused"
    planned = "planned"
    started = "started"


class ProjectTab(str, Enum):
    documents = "documents"
    issues = "issues"


class ProjectUpdateHealthType(str, Enum):
    atRisk = "atRisk"
    offTrack = "offTrack"
    onTrack = "onTrack"


class ProjectUpdateReminderFrequency(str, Enum):
    month = "month"
    never = "never"
    twoWeeks = "twoWeeks"
    week = "week"


class PushSubscriptionType(str, Enum):
    apple = "apple"
    appleDevelopment = "appleDevelopment"
    firebase = "firebase"
    web = "web"


class ReleaseChannel(str, Enum):
    beta = "beta"
    internal = "internal"
    preRelease = "preRelease"
    public = "public"


class SLADayCountType(str, Enum):
    all = "all"
    onlyBusinessDays = "onlyBusinessDays"


class SchemaFieldType(str, Enum):
    booleanType = "booleanType"
    dateType = "dateType"
    numberType = "numberType"
    stringType = "stringType"


class SendStrategy(str, Enum):
    desktop = "desktop"
    desktopAndPush = "desktopAndPush"
    desktopThenPush = "desktopThenPush"
    push = "push"


class SlaStatus(str, Enum):
    Breached = "Breached"
    Completed = "Completed"
    Failed = "Failed"
    HighRisk = "HighRisk"
    LowRisk = "LowRisk"
    MediumRisk = "MediumRisk"


class SlackChannelType(str, Enum):
    DirectMessage = "DirectMessage"
    MultiPersonDirectMessage = "MultiPersonDirectMessage"
    Private = "Private"
    Public = "Public"


class TriageResponsibilityAction(str, Enum):
    assign = "assign"
    notify = "notify"


class UserContextViewType(str, Enum):
    assigned = "assigned"


class UserFlagType(str, Enum):
    all = "all"
    analyticsWelcomeDismissed = "analyticsWelcomeDismissed"
    canPlaySnake = "canPlaySnake"
    canPlayTetris = "canPlayTetris"
    completedOnboarding = "completedOnboarding"
    cycleWelcomeDismissed = "cycleWelcomeDismissed"
    desktopDownloadToastDismissed = "desktopDownloadToastDismissed"
    desktopInstalled = "desktopInstalled"
    desktopTabsOnboardingDismissed = "desktopTabsOnboardingDismissed"
    dueDateShortcutMigration = "dueDateShortcutMigration"
    editorSlashCommandUsed = "editorSlashCommandUsed"
    emptyActiveIssuesDismissed = "emptyActiveIssuesDismissed"
    emptyBacklogDismissed = "emptyBacklogDismissed"
    emptyCustomViewsDismissed = "emptyCustomViewsDismissed"
    emptyMyIssuesDismissed = "emptyMyIssuesDismissed"
    emptyParagraphSlashCommandTip = "emptyParagraphSlashCommandTip"
    figmaPluginBannerDismissed = "figmaPluginBannerDismissed"
    figmaPromptDismissed = "figmaPromptDismissed"
    helpIslandFeatureInsightsDismissed = "helpIslandFeatureInsightsDismissed"
    importBannerDismissed = "importBannerDismissed"
    initiativesBannerDismissed = "initiativesBannerDismissed"
    insightsHelpDismissed = "insightsHelpDismissed"
    insightsWelcomeDismissed = "insightsWelcomeDismissed"
    issueLabelSuggestionUsed = "issueLabelSuggestionUsed"
    issueMovePromptCompleted = "issueMovePromptCompleted"
    joinTeamIntroductionDismissed = "joinTeamIntroductionDismissed"
    listSelectionTip = "listSelectionTip"
    migrateThemePreference = "migrateThemePreference"
    milestoneOnboardingIsSeenAndDismissed = "milestoneOnboardingIsSeenAndDismissed"
    projectBacklogWelcomeDismissed = "projectBacklogWelcomeDismissed"
    projectBoardOnboardingIsSeenAndDismissed = (
        "projectBoardOnboardingIsSeenAndDismissed"
    )
    projectUpdatesWelcomeDismissed = "projectUpdatesWelcomeDismissed"
    projectWelcomeDismissed = "projectWelcomeDismissed"
    rewindBannerDismissed = "rewindBannerDismissed"
    slackCommentReactionTipShown = "slackCommentReactionTipShown"
    teamsPageIntroductionDismissed = "teamsPageIntroductionDismissed"
    threadedCommentsNudgeIsSeen = "threadedCommentsNudgeIsSeen"
    triageWelcomeDismissed = "triageWelcomeDismissed"
    tryCyclesDismissed = "tryCyclesDismissed"
    tryGithubDismissed = "tryGithubDismissed"
    tryInvitePeopleDismissed = "tryInvitePeopleDismissed"
    tryRoadmapsDismissed = "tryRoadmapsDismissed"
    tryTriageDismissed = "tryTriageDismissed"
    updatedSlackThreadSyncIntegration = "updatedSlackThreadSyncIntegration"


class UserFlagUpdateOperation(str, Enum):
    clear = "clear"
    decr = "decr"
    incr = "incr"
    lock = "lock"


class UserRoleType(str, Enum):
    admin = "admin"
    guest = "guest"
    user = "user"


class ViewPreferencesType(str, Enum):
    organization = "organization"
    user = "user"


class ViewType(str, Enum):
    activeIssues = "activeIssues"
    allIssues = "allIssues"
    archive = "archive"
    backlog = "backlog"
    board = "board"
    completedCycle = "completedCycle"
    customRoadmap = "customRoadmap"
    customView = "customView"
    customViews = "customViews"
    customers = "customers"
    cycle = "cycle"
    inbox = "inbox"
    initiative = "initiative"
    initiativeOverview = "initiativeOverview"
    initiatives = "initiatives"
    initiativesCompleted = "initiativesCompleted"
    initiativesPlanned = "initiativesPlanned"
    issueIdentifiers = "issueIdentifiers"
    label = "label"
    myIssues = "myIssues"
    myIssuesActivity = "myIssuesActivity"
    myIssuesCreatedByMe = "myIssuesCreatedByMe"
    myIssuesSubscribedTo = "myIssuesSubscribedTo"
    project = "project"
    projectDocuments = "projectDocuments"
    projects = "projects"
    projectsAll = "projectsAll"
    projectsBacklog = "projectsBacklog"
    projectsClosed = "projectsClosed"
    quickView = "quickView"
    roadmap = "roadmap"
    roadmapAll = "roadmapAll"
    roadmapBacklog = "roadmapBacklog"
    roadmapClosed = "roadmapClosed"
    roadmaps = "roadmaps"
    search = "search"
    splitSearch = "splitSearch"
    teams = "teams"
    triage = "triage"
    userProfile = "userProfile"
    userProfileCreatedByUser = "userProfileCreatedByUser"


class WorkflowTrigger(str, Enum):
    entityCreated = "entityCreated"
    entityCreatedOrUpdated = "entityCreatedOrUpdated"
    entityRemoved = "entityRemoved"
    entityUnarchived = "entityUnarchived"
    entityUpdated = "entityUpdated"


class WorkflowTriggerType(str, Enum):
    issue = "issue"
    project = "project"


class WorkflowType(str, Enum):
    custom = "custom"
    sla = "sla"
    viewSubscription = "viewSubscription"
