# Generated by ariadne-codegen
# Source: src/release_helper/issue_management/linear/schema.graphql

from enum import Enum


class AuthenticationSessionType(str, Enum):
    android = "android"
    desktop = "desktop"
    ios = "ios"
    web = "web"


class ContextViewType(str, Enum):
    activeCycle = "activeCycle"
    activeIssues = "activeIssues"
    backlog = "backlog"
    triage = "triage"
    upcomingCycle = "upcomingCycle"


class CustomerStatusType(str, Enum):
    active = "active"
    inactive = "inactive"


class CyclePeriod(str, Enum):
    after = "after"
    before = "before"
    during = "during"


class DateResolutionType(str, Enum):
    halfYear = "halfYear"
    month = "month"
    quarter = "quarter"
    year = "year"


class Day(str, Enum):
    Friday = "Friday"
    Monday = "Monday"
    Saturday = "Saturday"
    Sunday = "Sunday"
    Thursday = "Thursday"
    Tuesday = "Tuesday"
    Wednesday = "Wednesday"


class ExternalSyncService(str, Enum):
    github = "github"
    jira = "jira"
    slack = "slack"


class FacetPageSource(str, Enum):
    feed = "feed"
    projects = "projects"
    teamIssues = "teamIssues"


class FeedSummarySchedule(str, Enum):
    daily = "daily"
    never = "never"
    weekly = "weekly"


class FrequencyResolutionType(str, Enum):
    daily = "daily"
    weekly = "weekly"


class GitAutomationStates(str, Enum):
    draft = "draft"
    merge = "merge"
    mergeable = "mergeable"
    review = "review"
    start = "start"


class GitLinkKind(str, Enum):
    closes = "closes"
    contributes = "contributes"
    links = "links"


class GithubOrgType(str, Enum):
    organization = "organization"
    user = "user"


class InitiativeStatus(str, Enum):
    Active = "Active"
    Completed = "Completed"
    Planned = "Planned"


class InitiativeTab(str, Enum):
    overview = "overview"
    projects = "projects"


class InitiativeUpdateHealthType(str, Enum):
    atRisk = "atRisk"
    offTrack = "offTrack"
    onTrack = "onTrack"


class IntegrationService(str, Enum):
    airbyte = "airbyte"
    discord = "discord"
    email = "email"
    figma = "figma"
    figmaPlugin = "figmaPlugin"
    front = "front"
    github = "github"
    githubCommit = "githubCommit"
    githubEnterpriseServer = "githubEnterpriseServer"
    githubImport = "githubImport"
    githubPersonal = "githubPersonal"
    gitlab = "gitlab"
    googleCalendarPersonal = "googleCalendarPersonal"
    googleSheets = "googleSheets"
    intercom = "intercom"
    jira = "jira"
    jiraPersonal = "jiraPersonal"
    launchDarkly = "launchDarkly"
    launchDarklyPersonal = "launchDarklyPersonal"
    loom = "loom"
    notion = "notion"
    opsgenie = "opsgenie"
    pagerDuty = "pagerDuty"
    salesforce = "salesforce"
    sentry = "sentry"
    slack = "slack"
    slackAsks = "slackAsks"
    slackCustomViewNotifications = "slackCustomViewNotifications"
    slackInitiativePost = "slackInitiativePost"
    slackOrgInitiativeUpdatesPost = "slackOrgInitiativeUpdatesPost"
    slackOrgProjectUpdatesPost = "slackOrgProjectUpdatesPost"
    slackPersonal = "slackPersonal"
    slackPost = "slackPost"
    slackProjectPost = "slackProjectPost"
    slackProjectUpdatesPost = "slackProjectUpdatesPost"
    zendesk = "zendesk"


class IssueRelationType(str, Enum):
    blocks = "blocks"
    duplicate = "duplicate"
    related = "related"
    similar = "similar"


class IssueSuggestionState(str, Enum):
    accepted = "accepted"
    active = "active"
    dismissed = "dismissed"
    stale = "stale"


class IssueSuggestionType(str, Enum):
    assignee = "assignee"
    label = "label"
    project = "project"
    relatedIssue = "relatedIssue"
    similarIssue = "similarIssue"
    team = "team"


class NotificationCategory(str, Enum):
    appsAndIntegrations = "appsAndIntegrations"
    assignments = "assignments"
    commentsAndReplies = "commentsAndReplies"
    customers = "customers"
    documentChanges = "documentChanges"
    mentions = "mentions"
    postsAndUpdates = "postsAndUpdates"
    reactions = "reactions"
    reminders = "reminders"
    reviews = "reviews"
    statusChanges = "statusChanges"
    subscriptions = "subscriptions"
    system = "system"
    triage = "triage"


class NotificationChannel(str, Enum):
    desktop = "desktop"
    email = "email"
    mobile = "mobile"
    slack = "slack"


class OAuthClientApprovalStatus(str, Enum):
    approved = "approved"
    denied = "denied"
    requested = "requested"


class OrganizationDomainAuthType(str, Enum):
    general = "general"
    saml = "saml"


class OrganizationInviteStatus(str, Enum):
    accepted = "accepted"
    expired = "expired"
    pending = "pending"


class OtherNotificationType(str, Enum):
    customerAddedAsOwner = "customerAddedAsOwner"
    customerNeedCreated = "customerNeedCreated"
    customerNeedMarkedAsImportant = "customerNeedMarkedAsImportant"
    customerNeedResolved = "customerNeedResolved"
    documentCommentMention = "documentCommentMention"
    documentCommentReaction = "documentCommentReaction"
    documentContentChange = "documentContentChange"
    documentDeleted = "documentDeleted"
    documentMention = "documentMention"
    documentMoved = "documentMoved"
    documentNewComment = "documentNewComment"
    documentReminder = "documentReminder"
    documentRestored = "documentRestored"
    documentSubscribed = "documentSubscribed"
    documentThreadResolved = "documentThreadResolved"
    documentUnsubscribed = "documentUnsubscribed"
    feedSummaryGenerated = "feedSummaryGenerated"
    initiativeAddedAsOwner = "initiativeAddedAsOwner"
    initiativeCommentMention = "initiativeCommentMention"
    initiativeCommentReaction = "initiativeCommentReaction"
    initiativeDescriptionContentChange = "initiativeDescriptionContentChange"
    initiativeMention = "initiativeMention"
    initiativeNewComment = "initiativeNewComment"
    initiativeReminder = "initiativeReminder"
    initiativeThreadResolved = "initiativeThreadResolved"
    initiativeUpdateCommentMention = "initiativeUpdateCommentMention"
    initiativeUpdateCommentReaction = "initiativeUpdateCommentReaction"
    initiativeUpdateCreated = "initiativeUpdateCreated"
    initiativeUpdateMention = "initiativeUpdateMention"
    initiativeUpdateNewComment = "initiativeUpdateNewComment"
    initiativeUpdatePrompt = "initiativeUpdatePrompt"
    initiativeUpdateReaction = "initiativeUpdateReaction"
    issueAddedToTriage = "issueAddedToTriage"
    issueAddedToView = "issueAddedToView"
    issueBlocking = "issueBlocking"
    issueCreated = "issueCreated"
    issueDue = "issueDue"
    issuePriorityUrgent = "issuePriorityUrgent"
    issueReminder = "issueReminder"
    issueReopened = "issueReopened"
    issueSlaBreached = "issueSlaBreached"
    issueSlaHighRisk = "issueSlaHighRisk"
    issueStatusChangedAll = "issueStatusChangedAll"
    issueSubscribed = "issueSubscribed"
    issueThreadResolved = "issueThreadResolved"
    issueUnblocked = "issueUnblocked"
    issueUnsubscribed = "issueUnsubscribed"
    oauthClientApprovalCreated = "oauthClientApprovalCreated"
    projectAddedAsLead = "projectAddedAsLead"
    projectAddedAsMember = "projectAddedAsMember"
    projectCommentMention = "projectCommentMention"
    projectCommentReaction = "projectCommentReaction"
    projectDescriptionContentChange = "projectDescriptionContentChange"
    projectMention = "projectMention"
    projectMilestoneCommentMention = "projectMilestoneCommentMention"
    projectMilestoneCommentReaction = "projectMilestoneCommentReaction"
    projectMilestoneDescriptionContentChange = (
        "projectMilestoneDescriptionContentChange"
    )
    projectMilestoneMention = "projectMilestoneMention"
    projectMilestoneNewComment = "projectMilestoneNewComment"
    projectMilestoneThreadResolved = "projectMilestoneThreadResolved"
    projectNewComment = "projectNewComment"
    projectReminder = "projectReminder"
    projectThreadResolved = "projectThreadResolved"
    projectUpdateCommentMention = "projectUpdateCommentMention"
    projectUpdateCommentReaction = "projectUpdateCommentReaction"
    projectUpdateCreated = "projectUpdateCreated"
    projectUpdateMention = "projectUpdateMention"
    projectUpdateNewComment = "projectUpdateNewComment"
    projectUpdatePrompt = "projectUpdatePrompt"
    projectUpdateReaction = "projectUpdateReaction"
    pullRequestApproved = "pullRequestApproved"
    pullRequestChangesRequested = "pullRequestChangesRequested"
    pullRequestChecksFailed = "pullRequestChecksFailed"
    pullRequestCommentMention = "pullRequestCommentMention"
    pullRequestCommented = "pullRequestCommented"
    pullRequestMention = "pullRequestMention"
    pullRequestRemovedFromMergeQueue = "pullRequestRemovedFromMergeQueue"
    pullRequestReviewRequested = "pullRequestReviewRequested"
    pullRequestReviewRerequested = "pullRequestReviewRerequested"
    system = "system"
    teamUpdateCommentMention = "teamUpdateCommentMention"
    teamUpdateCommentReaction = "teamUpdateCommentReaction"
    teamUpdateCreated = "teamUpdateCreated"
    teamUpdateMention = "teamUpdateMention"
    teamUpdateNewComment = "teamUpdateNewComment"
    teamUpdateReaction = "teamUpdateReaction"
    triageResponsibilityIssueAddedToTriage = "triageResponsibilityIssueAddedToTriage"


class PaginationNulls(str, Enum):
    first = "first"
    last = "last"


class PaginationOrderBy(str, Enum):
    createdAt = "createdAt"
    updatedAt = "updatedAt"


class PaginationSortOrder(str, Enum):
    Ascending = "Ascending"
    Descending = "Descending"


class PostType(str, Enum):
    summary = "summary"
    update = "update"


class ProductIntelligenceScope(str, Enum):
    none = "none"
    team = "team"
    teamHierarchy = "teamHierarchy"
    workspace = "workspace"


class ProjectMilestoneStatus(str, Enum):
    done = "done"
    next = "next"
    overdue = "overdue"
    unstarted = "unstarted"


class ProjectStatusType(str, Enum):
    backlog = "backlog"
    canceled = "canceled"
    completed = "completed"
    paused = "paused"
    planned = "planned"
    started = "started"


class ProjectTab(str, Enum):
    customers = "customers"
    documents = "documents"
    issues = "issues"


class ProjectUpdateHealthType(str, Enum):
    atRisk = "atRisk"
    offTrack = "offTrack"
    onTrack = "onTrack"


class ProjectUpdateReminderFrequency(str, Enum):
    month = "month"
    never = "never"
    twoWeeks = "twoWeeks"
    week = "week"


class PullRequestReviewTool(str, Enum):
    graphite = "graphite"
    source = "source"


class PullRequestStatus(str, Enum):
    approved = "approved"
    closed = "closed"
    draft = "draft"
    inReview = "inReview"
    merged = "merged"
    open = "open"


class PushSubscriptionType(str, Enum):
    apple = "apple"
    appleDevelopment = "appleDevelopment"
    firebase = "firebase"
    web = "web"


class ReleaseChannel(str, Enum):
    beta = "beta"
    development = "development"
    internal = "internal"
    preRelease = "preRelease"
    public = "public"


class SLADayCountType(str, Enum):
    all = "all"
    onlyBusinessDays = "onlyBusinessDays"


class SemanticSearchResultType(str, Enum):
    document = "document"
    initiative = "initiative"
    issue = "issue"
    project = "project"


class SendStrategy(str, Enum):
    desktop = "desktop"
    desktopAndPush = "desktopAndPush"
    desktopThenPush = "desktopThenPush"
    push = "push"


class SlaStatus(str, Enum):
    Breached = "Breached"
    Completed = "Completed"
    Failed = "Failed"
    HighRisk = "HighRisk"
    LowRisk = "LowRisk"
    MediumRisk = "MediumRisk"


class SlackChannelType(str, Enum):
    DirectMessage = "DirectMessage"
    MultiPersonDirectMessage = "MultiPersonDirectMessage"
    Private = "Private"
    Public = "Public"


class TriageResponsibilityAction(str, Enum):
    assign = "assign"
    notify = "notify"


class UserContextViewType(str, Enum):
    assigned = "assigned"


class UserFlagType(str, Enum):
    all = "all"
    analyticsWelcomeDismissed = "analyticsWelcomeDismissed"
    canPlaySnake = "canPlaySnake"
    canPlayTetris = "canPlayTetris"
    commandMenuClearShortcutTip = "commandMenuClearShortcutTip"
    completedOnboarding = "completedOnboarding"
    cycleWelcomeDismissed = "cycleWelcomeDismissed"
    desktopDownloadToastDismissed = "desktopDownloadToastDismissed"
    desktopInstalled = "desktopInstalled"
    desktopTabsOnboardingDismissed = "desktopTabsOnboardingDismissed"
    dueDateShortcutMigration = "dueDateShortcutMigration"
    editorSlashCommandUsed = "editorSlashCommandUsed"
    emptyActiveIssuesDismissed = "emptyActiveIssuesDismissed"
    emptyBacklogDismissed = "emptyBacklogDismissed"
    emptyCustomViewsDismissed = "emptyCustomViewsDismissed"
    emptyMyIssuesDismissed = "emptyMyIssuesDismissed"
    emptyParagraphSlashCommandTip = "emptyParagraphSlashCommandTip"
    figmaPluginBannerDismissed = "figmaPluginBannerDismissed"
    figmaPromptDismissed = "figmaPromptDismissed"
    helpIslandFeatureInsightsDismissed = "helpIslandFeatureInsightsDismissed"
    importBannerDismissed = "importBannerDismissed"
    initiativesBannerDismissed = "initiativesBannerDismissed"
    insightsHelpDismissed = "insightsHelpDismissed"
    insightsWelcomeDismissed = "insightsWelcomeDismissed"
    issueLabelSuggestionUsed = "issueLabelSuggestionUsed"
    issueMovePromptCompleted = "issueMovePromptCompleted"
    joinTeamIntroductionDismissed = "joinTeamIntroductionDismissed"
    listSelectionTip = "listSelectionTip"
    migrateThemePreference = "migrateThemePreference"
    milestoneOnboardingIsSeenAndDismissed = "milestoneOnboardingIsSeenAndDismissed"
    projectBacklogWelcomeDismissed = "projectBacklogWelcomeDismissed"
    projectBoardOnboardingIsSeenAndDismissed = (
        "projectBoardOnboardingIsSeenAndDismissed"
    )
    projectUpdatesWelcomeDismissed = "projectUpdatesWelcomeDismissed"
    projectWelcomeDismissed = "projectWelcomeDismissed"
    pulseWelcomeDismissed = "pulseWelcomeDismissed"
    rewindBannerDismissed = "rewindBannerDismissed"
    slackCommentReactionTipShown = "slackCommentReactionTipShown"
    teamsPageIntroductionDismissed = "teamsPageIntroductionDismissed"
    threadedCommentsNudgeIsSeen = "threadedCommentsNudgeIsSeen"
    triageWelcomeDismissed = "triageWelcomeDismissed"
    tryCyclesDismissed = "tryCyclesDismissed"
    tryGithubDismissed = "tryGithubDismissed"
    tryInvitePeopleDismissed = "tryInvitePeopleDismissed"
    tryRoadmapsDismissed = "tryRoadmapsDismissed"
    tryTriageDismissed = "tryTriageDismissed"
    updatedSlackThreadSyncIntegration = "updatedSlackThreadSyncIntegration"


class UserFlagUpdateOperation(str, Enum):
    clear = "clear"
    decr = "decr"
    incr = "incr"
    lock = "lock"


class UserRoleType(str, Enum):
    admin = "admin"
    app = "app"
    guest = "guest"
    user = "user"


class ViewPreferencesType(str, Enum):
    organization = "organization"
    user = "user"


class ViewType(str, Enum):
    activeIssues = "activeIssues"
    allIssues = "allIssues"
    archive = "archive"
    backlog = "backlog"
    board = "board"
    completedCycle = "completedCycle"
    customRoadmap = "customRoadmap"
    customView = "customView"
    customViews = "customViews"
    customer = "customer"
    customers = "customers"
    cycle = "cycle"
    dashboards = "dashboards"
    embeddedCustomerNeeds = "embeddedCustomerNeeds"
    feedAll = "feedAll"
    feedCreated = "feedCreated"
    feedFollowing = "feedFollowing"
    feedPopular = "feedPopular"
    inbox = "inbox"
    initiative = "initiative"
    initiativeOverview = "initiativeOverview"
    initiativeOverviewSubInitiatives = "initiativeOverviewSubInitiatives"
    initiatives = "initiatives"
    initiativesCompleted = "initiativesCompleted"
    initiativesPlanned = "initiativesPlanned"
    issueIdentifiers = "issueIdentifiers"
    label = "label"
    myIssues = "myIssues"
    myIssuesActivity = "myIssuesActivity"
    myIssuesCreatedByMe = "myIssuesCreatedByMe"
    myIssuesSubscribedTo = "myIssuesSubscribedTo"
    myReviews = "myReviews"
    project = "project"
    projectCustomerNeeds = "projectCustomerNeeds"
    projectDocuments = "projectDocuments"
    projectLabel = "projectLabel"
    projects = "projects"
    projectsAll = "projectsAll"
    projectsBacklog = "projectsBacklog"
    projectsClosed = "projectsClosed"
    quickView = "quickView"
    reviews = "reviews"
    roadmap = "roadmap"
    roadmapAll = "roadmapAll"
    roadmapBacklog = "roadmapBacklog"
    roadmapClosed = "roadmapClosed"
    roadmaps = "roadmaps"
    search = "search"
    splitSearch = "splitSearch"
    subIssues = "subIssues"
    teams = "teams"
    triage = "triage"
    userProfile = "userProfile"
    userProfileCreatedByUser = "userProfileCreatedByUser"
    workspaceMembers = "workspaceMembers"
