# Generated by ariadne-codegen
# Source: src/release_helper/issue_management/linear/queries.graphql

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class Issue(BaseModel):
    issue: "IssueIssue"


class IssueIssue(BaseModel):
    id: str
    title: str
    description: Optional[str]
    priority: float
    priority_label: str = Field(alias="priorityLabel")
    created_at: Any = Field(alias="createdAt")
    completed_at: Optional[Any] = Field(alias="completedAt")
    state: "IssueIssueState"
    assignee: Optional["IssueIssueAssignee"]
    url: str
    identifier: str
    team: "IssueIssueTeam"
    labels: "IssueIssueLabels"
    project: Optional["IssueIssueProject"]


class IssueIssueState(BaseModel):
    name: str
    type: str
    id: str
    description: Optional[str]
    color: str


class IssueIssueAssignee(BaseModel):
    id: str
    name: str
    display_name: str = Field(alias="displayName")
    url: str
    email: str


class IssueIssueTeam(BaseModel):
    key: str
    name: str


class IssueIssueLabels(BaseModel):
    nodes: List["IssueIssueLabelsNodes"]


class IssueIssueLabelsNodes(BaseModel):
    id: str
    name: str
    color: str


class IssueIssueProject(BaseModel):
    id: str
    name: str
    description: str
    url: str


Issue.model_rebuild()
IssueIssue.model_rebuild()
IssueIssueLabels.model_rebuild()
