# Generated by ariadne-codegen on 2023-05-16 16:35
# Source: queries.graphql

# Third Party
from pydantic import Field

from .base_model import BaseModel


class State(BaseModel):
    workflow_states: "StateWorkflowStates" = Field(alias="workflowStates")


class StateWorkflowStates(BaseModel):
    nodes: list["StateWorkflowStatesNodes"]


class StateWorkflowStatesNodes(BaseModel):
    id: str


State.update_forward_refs()
StateWorkflowStates.update_forward_refs()
StateWorkflowStatesNodes.update_forward_refs()
