# Generated by ariadne-codegen on 2023-05-16 16:35
# Source: queries.graphql

# Standard Library
from typing import Optional

# Third Party
from pydantic import Field

from .base_model import BaseModel


class Issue(BaseModel):
    issue: "IssueIssue"


class IssueIssue(BaseModel):
    id: str
    title: str
    state: "IssueIssueState"
    assignee: Optional["IssueIssueAssignee"]
    url: str
    identifier: str


class IssueIssueState(BaseModel):
    name: str
    type: str
    id: str
    description: str | None
    color: str


class IssueIssueAssignee(BaseModel):
    id: str
    name: str
    display_name: str = Field(alias="displayName")
    url: str
    email: str


Issue.update_forward_refs()
IssueIssue.update_forward_refs()
IssueIssueState.update_forward_refs()
IssueIssueAssignee.update_forward_refs()
