# Generated by ariadne-codegen on 2023-05-16 16:35
# Source: queries.graphql

# Third Party
from pydantic import Field

from .base_model import BaseModel


class IssueUpdate(BaseModel):
    issue_update: "IssueUpdateIssueUpdate" = Field(alias="issueUpdate")


class IssueUpdateIssueUpdate(BaseModel):
    success: bool


IssueUpdate.update_forward_refs()
IssueUpdateIssueUpdate.update_forward_refs()
