# Generated by ariadne-codegen on 2023-05-16 16:35

# Standard Library
from collections.abc import Callable
from typing import Any


SCALARS_PARSE_FUNCTIONS: dict[Any, Callable[[str], Any]] = {}
SCALARS_SERIALIZE_FUNCTIONS: dict[Any, Callable[[Any], str]] = {}
