query Issue($issueId: String!) {
    issue(id: $issueId) {
        id
        title
        description
        priority
        priorityLabel
        createdAt
        completedAt
        state {
            name
            type
            id
            description
            color
        }
        assignee {
            id
            name
            displayName
            url
            email
        }
        url
        identifier
        team {
            key
            name
        }
        labels {
            nodes {
                id
                name
                color
            }
        }
        project {
            id
            name
            description
            url
            initiatives {
                nodes {
                    id
                    name
                    description
                }
            }
        }
    }
}

query State($filter: WorkflowStateFilter) {
    workflowStates(filter: $filter) {
        nodes {
            id
        }
    }
}

mutation IssueUpdate($input: IssueUpdateInput!, $issueId: String!) {
    issueUpdate(id: $issueId, input: $input) {
        success
    }
}
